# Series

In [2]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
a = pd.Series([1,2,3,'a','b','g'])
a

0    1
1    2
2    3
3    a
4    b
5    g
dtype: object

In [3]:
b = pd.Series([1,2,3,4,5,6,7],index = ['r1','r2','r3','r4','r5','r6','r7'],dtype = 'float')
b

r1    1.0
r2    2.0
r3    3.0
r4    4.0
r5    5.0
r6    6.0
r7    7.0
dtype: float64

In [4]:
b['r2']

2.0

In [5]:
a = pd.Series([1,2,3,4,5,4,5,6],['a','b','c','d','e','f','g','h'])

In [6]:
a

a    1
b    2
c    3
d    4
e    5
f    4
g    5
h    6
dtype: int64

In [7]:
b = Series(np.arange(8),index = ['r0','r1','r2','r3','r4','r5','r6','r7'])
b

r0    0
r1    1
r2    2
r3    3
r4    4
r5    5
r6    6
r7    7
dtype: int32

In [8]:
Series(np.arange(5))

0    0
1    1
2    2
3    3
4    4
dtype: int32

In [9]:
b['r1':'r5']

r1    1
r2    2
r3    3
r4    4
r5    5
dtype: int32

In [10]:
b[1:5]

r1    1
r2    2
r3    3
r4    4
dtype: int32

In [11]:
c = Series([1,2,3,4,5],index=['r1','r2','r3','r4','r5'])
c

r1    1
r2    2
r3    3
r4    4
r5    5
dtype: int64

In [12]:
c['r1':'r4']

r1    1
r2    2
r3    3
r4    4
dtype: int64

In [13]:
c[1:3]

r2    2
r3    3
dtype: int64

# Data Frame

In [14]:
a = DataFrame([[1,2,3,4,5,6,7],[1,2,3,4,5,1,2],['a','b','c','d','e','f','g']])

In [15]:
a

   0  1  2  3  4  5  6
0  1  2  3  4  5  6  7
1  1  2  3  4  5  1  2
2  a  b  c  d  e  f  g

In [16]:
a = DataFrame([[1,2,3,4],[5,6,7,8],[1,24,5,6]],columns = ['c1','c2','c3','c4'])

In [17]:
a

   c1  c2  c3  c4
0   1   2   3   4
1   5   6   7   8
2   1  24   5   6

In [18]:
# Factorial 

num = [3,4,5,6,7,8,9,10]
fact = 1

for item in num:
      
        for i in range(1,item+1):
            fact = fact*i
        print(i,fact)
        fact = 1

3 6
4 24
5 120
6 720
7 5040
8 40320
9 362880
10 3628800

In [19]:
a

   c1  c2  c3  c4
0   1   2   3   4
1   5   6   7   8
2   1  24   5   6

In [20]:
b = DataFrame(np.ceil(np.random.rand(36).reshape(9,4)*100))

In [21]:
c = DataFrame(np.floor(np.random.rand(50).reshape(10,5)*100))

In [22]:
c

      0     1     2     3     4
0  64.0  47.0  73.0  80.0  70.0
1  29.0  11.0  51.0  50.0  29.0
2  85.0  39.0  14.0  58.0  99.0
3  52.0  18.0  26.0  53.0  94.0
4  72.0  64.0  97.0  38.0  13.0
5  42.0  71.0  54.0  12.0  18.0
6   2.0  67.0   5.0  94.0  90.0
7  85.0  27.0  53.0  78.0  62.0
8  10.0   3.0  87.0  45.0  60.0
9  95.0  82.0  29.0  21.0  48.0

In [23]:
c.columns = ['c1','c2','c3','c4','c5']

In [24]:
c.index = ['r1','r2','r3','r4','r5','r6','r7','r8','r9','r10']
c

       c1    c2    c3    c4    c5
r1   64.0  47.0  73.0  80.0  70.0
r2   29.0  11.0  51.0  50.0  29.0
r3   85.0  39.0  14.0  58.0  99.0
r4   52.0  18.0  26.0  53.0  94.0
r5   72.0  64.0  97.0  38.0  13.0
r6   42.0  71.0  54.0  12.0  18.0
r7    2.0  67.0   5.0  94.0  90.0
r8   85.0  27.0  53.0  78.0  62.0
r9   10.0   3.0  87.0  45.0  60.0
r10  95.0  82.0  29.0  21.0  48.0

In [25]:
pwd

'C:\\Users\\Bharath\\Documents\\Practise\\Pandas'

# Importing the csv file

In [26]:
data = pd.read_csv('mtcars.csv')

In [27]:
data.head()

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [28]:
data.columns

Index(['car_model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')

In [29]:
data.shape

(32, 12)

In [30]:
data.isnull()

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,False,False

In [31]:
data.isnull().sum()

car_model    0
mpg          0
cyl          0
disp         0
hp           0
drat         0
wt           0
qsec         0
vs           0
am           0
gear         0
carb         0
dtype: int64

In [32]:
# Statistical Analysis
data.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [33]:
# Slicing the data loc[starting point(row):ending point(row),starting point(column):ending point(column)]

In [34]:
data.iloc[0:8,0:6]

           car_model   mpg  cyl   disp   hp  drat
0          Mazda RX4  21.0    6  160.0  110  3.90
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90
2         Datsun 710  22.8    4  108.0   93  3.85
3     Hornet 4 Drive  21.4    6  258.0  110  3.08
4  Hornet Sportabout  18.7    8  360.0  175  3.15
5            Valiant  18.1    6  225.0  105  2.76
6         Duster 360  14.3    8  360.0  245  3.21
7          Merc 240D  24.4    4  146.7   62  3.69

In [35]:
data.head(15)

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4

In [36]:
data.loc[1:10,['car_model','mpg','wt','am','carb']]

            car_model   mpg     wt  am  carb
1       Mazda RX4 Wag  21.0  2.875   1     4
2          Datsun 710  22.8  2.320   1     1
3      Hornet 4 Drive  21.4  3.215   0     1
4   Hornet Sportabout  18.7  3.440   0     2
5             Valiant  18.1  3.460   0     1
6          Duster 360  14.3  3.570   0     4
7           Merc 240D  24.4  3.190   0     2
8            Merc 230  22.8  3.150   0     2
9            Merc 280  19.2  3.440   0     4
10          Merc 280C  17.8  3.440   0     4

In [37]:
data.loc[10:18,'car_model':'gear']

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4

In [38]:
data.loc[data.hp==110,:]

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1

In [39]:
data.loc[(data.mpg>30) & (data.hp>110),:]

       car_model   mpg  cyl  disp   hp  drat     wt  qsec  vs  am  gear  carb
27  Lotus Europa  30.4    4  95.1  113  3.77  1.513  16.9   1   1     5     2

In [40]:
data.loc[(data.hp>150) | (data.gear>1)]

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

# Creating the new volume of eco car

In [41]:
data.loc[(data.mpg>=25),'eco_car'] = 1
data.loc[(data.mpg<25),'eco_car'] = 0
data.eco_car = data.eco_car.astype('int')

In [42]:
data.head(20)

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,eco_car
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,0
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,0
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,0
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,0
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,0
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,0
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,0
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,0
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,0
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,0
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,0
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,0
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,0
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,0
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,0
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,0
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,0
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,1
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,1

In [43]:
data.loc[(data.gear>=2)&(data.vs==0),'good_car'] = 1
data.loc[(data.gear<2)|(data.vs==1),'good_car'] = 0
data.good_car = data.good_car.astype('int')

In [44]:
data

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,eco_car,good_car
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,0,1
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,0,1
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,0,0
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,0,0
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,0,1
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,0,0
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,0,1
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,0,0
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,0,0
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,0,0
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,0,0
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,0,1
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,0,1
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,0,1
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,0,1
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,0,1
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,0,1
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,1,0
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,1,0
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,1,0
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,0,0
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,0,1
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,0,1
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,0,1
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,0,1
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,1,0
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,1,1
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,1,0
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,0,1
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,0,1
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,0,1
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,0,0

In [45]:
data.good_car = data.good_car.astype('int')

In [46]:
data.loc[(data.hp>=200),'Power_Car'] = 1
data.loc[(data.hp<200),'Power_Car'] = 0
data.Power_Car = data.Power_Car.astype('int')
data

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,eco_car,good_car,Power_Car
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,0,1,0
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,0,1,0
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,0,0,0
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,0,0,0
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,0,1,0
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,0,0,0
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,0,1,1
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,0,0,0
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,0,0,0
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,0,0,0
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,0,0,0
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,0,1,0
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,0,1,0
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,0,1,0
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,0,1,1
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,0,1,1
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,0,1,1
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,1,0,0
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,1,0,0
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,1,0,0
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,0,0,0
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,0,1,0
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,0,1,0
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,0,1,1
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,0,1,0
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,1,0,0
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,1,1,0
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,1,0,0
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,0,1,1
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,0,1,0
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,0,1,1
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,0,0,0

# calculate Alpha ration b/w mpg and hp

In [47]:
data.loc[:,'Alpha'] = data.hp/data.mpg

In [48]:
data.tail()

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,eco_car,good_car,Power_Car,Alpha
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.9,1,1,5,2,1,0,0,3.717105
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.5,0,1,5,4,0,1,1,16.708861
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.5,0,1,5,6,0,1,0,8.883249
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.6,0,1,5,8,0,1,1,22.333333
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.6,1,1,4,2,0,0,0,5.093458

In [58]:
data.isnull()

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,eco_car,good_car,Power_Car,Alpha
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [59]:
data.isnull().sum()

car_model    0
mpg          0
cyl          0
disp         0
hp           0
drat         0
wt           0
qsec         0
vs           0
am           0
gear         0
carb         0
eco_car      0
good_car     0
Power_Car    0
Alpha        0
dtype: int64

In [60]:
data.loc[data.eco_car==1]

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,eco_car,good_car,Power_Car,Alpha
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,1,0,0,2.037037
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,1,0,0,1.710526
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,1,0,0,1.917404
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,1,0,0,2.417582
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,1,1,0,3.500000
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,1,0,0,3.717105

# Data mugung,processing,Wranging and preparations

- Missing value
- Wrong value
- duplicates 
- formatting issues/Different values
- outliers

In [179]:
data = pd.read_csv('mtcars_missing.csv')
data.head(20)

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160,110.0,3.90,2.62,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,$,110.0,NaN,2.875,*,0,1,4,4
2,Datsun 710,NaN,4,108,NaN,3.85,?,18.61,1,1,4,1
3,Hornet 4 Drive,999.0,6,NaN,NaN,3.08,3.215,-,1,0,3,1
4,Datsun 710,22.8,4,NaN,93.0,3.85,2.32,18.61,1,1,4,1
5,Valiant,18.1,6,225,105.0,2.76,3.46,20.22,1,0,3,1
6,Duster 360,14.3,8,360,245.0,3.21,3.57,15.84,0,0,3,4
7,Valiant 2,18.1,6,225,105.0,2.76,3.46,20.22,1,0,3,1
8,Valiant,18.1,6,225,105.0,2.76,3.46,20.22,1,0,3,1
9,Merc 280,19.2,6,167.6,123.0,3.92,3.44,18.3,1,0,4,4
10,Merc 280C,17.8,6,167.6,123.0,3.92,3.44,18.9,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180.0,3.07,4.07,17.4,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180.0,3.07,3.73,17.6,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180.0,3.07,3.78,18,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472,205.0,2.93,5.25,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460,215.0,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440,230.0,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66.0,4.08,2.2,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52.0,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65.0,4.22,1.835,19.9,1,1,4,1

In [180]:
np.nan == np.nan

False

In [181]:
data.isnull().sum()

car_model    0
mpg          1
cyl          0
disp         2
hp           2
drat         1
wt           0
qsec         0
vs           0
am           0
gear         0
carb         0
dtype: int64

In [182]:
data.disp.sort_values(ascending = True)

1         $
2       108
20    120.1
26    120.3
31      121
29      145
0       160
9     167.6
10    167.6
5       225
8       225
7       225
11    275.8
12    275.8
13    275.8
30      301
22      304
21      318
23      350
28      351
6       360
24      400
16      440
15      460
14      472
19     71.1
18     75.7
17     78.7
25       79
27     95.1
3       NaN
4       NaN
Name: disp, dtype: object

In [188]:
data.head(20)

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160,110.0,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,NaN,110.0,NaN,2.875,NaN,0,1,4,4
2,Datsun 710,NaN,4,108,NaN,3.85,NaN,18.61,1,1,4,1
3,Hornet 4 Drive,NaN,6,NaN,NaN,3.08,3.215,NaN,1,0,3,1
4,Datsun 710,22.8,4,NaN,93.0,3.85,2.320,18.61,1,1,4,1
5,Valiant,18.1,6,225,105.0,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360,245.0,3.21,3.570,15.84,0,0,3,4
7,Valiant 2,18.1,6,225,105.0,2.76,3.460,20.22,1,0,3,1
8,Valiant,18.1,6,225,105.0,2.76,3.460,20.22,1,0,3,1
9,Merc 280,19.2,6,167.6,123.0,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123.0,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180.0,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180.0,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180.0,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472,205.0,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460,215.0,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440,230.0,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66.0,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52.0,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65.0,4.22,1.835,19.90,1,1,4,1

In [189]:
data.replace(['$','*','?','-'],np.nan,inplace = True) # Wrong values are treated as missing values

In [190]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
car_model    32 non-null object
mpg          30 non-null float64
cyl          32 non-null int64
disp         29 non-null object
hp           30 non-null float64
drat         31 non-null float64
wt           31 non-null float64
qsec         30 non-null float64
vs           32 non-null int64
am           32 non-null int64
gear         32 non-null int64
carb         32 non-null int64
dtypes: float64(5), int64(5), object(2)
memory usage: 3.1+ KB

In [191]:
data.mpg = data.mpg.astype('float')
data.drat = data.drat.astype('float')
data.qsec = data.qsec.astype('float')
data.wt = data.wt.astype('float')

In [192]:
data.loc[data.mpg>100,'mpg'] = np.nan

In [193]:
data.dropna()

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160,110.0,3.90,2.620,16.46,0,1,4,4
5,Valiant,18.1,6,225,105.0,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360,245.0,3.21,3.570,15.84,0,0,3,4
7,Valiant 2,18.1,6,225,105.0,2.76,3.460,20.22,1,0,3,1
8,Valiant,18.1,6,225,105.0,2.76,3.460,20.22,1,0,3,1
9,Merc 280,19.2,6,167.6,123.0,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123.0,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180.0,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180.0,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180.0,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472,205.0,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460,215.0,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440,230.0,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66.0,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52.0,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65.0,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97.0,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318,150.0,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304,150.0,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350,245.0,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400,175.0,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79,66.0,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91.0,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113.0,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351,264.0,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145,175.0,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301,335.0,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121,109.0,4.11,2.780,18.60,1,1,4,2

# Treating the missing values

- Number of missing values is < 5 then we will drop it

In [194]:
data.isnull().sum()

car_model    0
mpg          2
cyl          0
disp         3
hp           2
drat         1
wt           1
qsec         2
vs           0
am           0
gear         0
carb         0
dtype: int64

In [198]:
data.fillna(method = 'ffill',inplace = True)

In [199]:
data.isnull().sum()

car_model    0
mpg          0
cyl          0
disp         0
hp           0
drat         0
wt           0
qsec         0
vs           0
am           0
gear         0
carb         0
dtype: int64

In [200]:
data

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160,110.0,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160,110.0,3.90,2.875,16.46,0,1,4,4
2,Datsun 710,21.0,4,108,110.0,3.85,2.875,18.61,1,1,4,1
3,Hornet 4 Drive,21.0,6,108,110.0,3.08,3.215,18.61,1,0,3,1
4,Datsun 710,22.8,4,108,93.0,3.85,2.320,18.61,1,1,4,1
5,Valiant,18.1,6,225,105.0,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360,245.0,3.21,3.570,15.84,0,0,3,4
7,Valiant 2,18.1,6,225,105.0,2.76,3.460,20.22,1,0,3,1
8,Valiant,18.1,6,225,105.0,2.76,3.460,20.22,1,0,3,1
9,Merc 280,19.2,6,167.6,123.0,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123.0,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180.0,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180.0,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180.0,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472,205.0,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460,215.0,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440,230.0,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66.0,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52.0,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65.0,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97.0,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318,150.0,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304,150.0,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350,245.0,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400,175.0,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79,66.0,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91.0,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113.0,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351,264.0,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145,175.0,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301,335.0,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121,109.0,4.11,2.780,18.60,1,1,4,2

In [201]:
data.fillna(data.mean())

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160,110.0,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160,110.0,3.90,2.875,16.46,0,1,4,4
2,Datsun 710,21.0,4,108,110.0,3.85,2.875,18.61,1,1,4,1
3,Hornet 4 Drive,21.0,6,108,110.0,3.08,3.215,18.61,1,0,3,1
4,Datsun 710,22.8,4,108,93.0,3.85,2.320,18.61,1,1,4,1
5,Valiant,18.1,6,225,105.0,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360,245.0,3.21,3.570,15.84,0,0,3,4
7,Valiant 2,18.1,6,225,105.0,2.76,3.460,20.22,1,0,3,1
8,Valiant,18.1,6,225,105.0,2.76,3.460,20.22,1,0,3,1
9,Merc 280,19.2,6,167.6,123.0,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123.0,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180.0,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180.0,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180.0,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472,205.0,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460,215.0,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440,230.0,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66.0,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52.0,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65.0,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97.0,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318,150.0,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304,150.0,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350,245.0,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400,175.0,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79,66.0,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91.0,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113.0,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351,264.0,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145,175.0,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301,335.0,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121,109.0,4.11,2.780,18.60,1,1,4,2

In [202]:
# Dropping the columns

In [205]:
data.drop(columns=['hp','drat','qsec'])

              car_model   mpg  cyl   disp     wt  vs  am  gear  carb
0             Mazda RX4  21.0    6    160  2.620   0   1     4     4
1         Mazda RX4 Wag  21.0    6    160  2.875   0   1     4     4
2            Datsun 710  21.0    4    108  2.875   1   1     4     1
3        Hornet 4 Drive  21.0    6    108  3.215   1   0     3     1
4            Datsun 710  22.8    4    108  2.320   1   1     4     1
5               Valiant  18.1    6    225  3.460   1   0     3     1
6            Duster 360  14.3    8    360  3.570   0   0     3     4
7             Valiant 2  18.1    6    225  3.460   1   0     3     1
8               Valiant  18.1    6    225  3.460   1   0     3     1
9              Merc 280  19.2    6  167.6  3.440   1   0     4     4
10            Merc 280C  17.8    6  167.6  3.440   1   0     4     4
11           Merc 450SE  16.4    8  275.8  4.070   0   0     3     3
12           Merc 450SL  17.3    8  275.8  3.730   0   0     3     3
13          Merc 450SLC  15.2    8  275.8  3.780   0   0     3     3
14   Cadillac Fleetwood  10.4    8    472  5.250   0   0     3     4
15  Lincoln Continental  10.4    8    460  5.424   0   0     3     4
16    Chrysler Imperial  14.7    8    440  5.345   0   0     3     4
17             Fiat 128  32.4    4   78.7  2.200   1   1     4     1
18          Honda Civic  30.4    4   75.7  1.615   1   1     4     2
19       Toyota Corolla  33.9    4   71.1  1.835   1   1     4     1
20        Toyota Corona  21.5    4  120.1  2.465   1   0     3     1
21     Dodge Challenger  15.5    8    318  3.520   0   0     3     2
22          AMC Javelin  15.2    8    304  3.435   0   0     3     2
23           Camaro Z28  13.3    8    350  3.840   0   0     3     4
24     Pontiac Firebird  19.2    8    400  3.845   0   0     3     2
25            Fiat X1-9  27.3    4     79  1.935   1   1     4     1
26        Porsche 914-2  26.0    4  120.3  2.140   0   1     5     2
27         Lotus Europa  30.4    4   95.1  1.513   1   1     5     2
28       Ford Pantera L  15.8    8    351  3.170   0   1     5     4
29         Ferrari Dino  19.7    6    145  2.770   0   1     5     6
30        Maserati Bora  15.0    8    301  3.570   0   1     5     8
31           Volvo 142E  21.4    4    121  2.780   1   1     4     2

In [211]:
data.drop(index = [2,3,6,13],inplace = True)

In [216]:
data.drop([1,5,7,17,18],axis = 'rows')

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160,110.0,3.90,2.620,16.46,0,1,4,4
4,Datsun 710,22.8,4,108,93.0,3.85,2.320,18.61,1,1,4,1
8,Valiant,18.1,6,225,105.0,2.76,3.460,20.22,1,0,3,1
9,Merc 280,19.2,6,167.6,123.0,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123.0,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180.0,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180.0,3.07,3.730,17.60,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472,205.0,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460,215.0,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440,230.0,3.23,5.345,17.42,0,0,3,4
19,Toyota Corolla,33.9,4,71.1,65.0,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97.0,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318,150.0,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304,150.0,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350,245.0,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400,175.0,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79,66.0,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91.0,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113.0,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351,264.0,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145,175.0,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301,335.0,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121,109.0,4.11,2.780,18.60,1,1,4,2

# Duplicates

In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv('mtcars_duplicates.csv')
data.head(9)

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,NaN,2.875,17.02,0,1,4,4
2,Datsun 710,21.0,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,22.8,6,108.0,110,3.08,3.215,19.44,1,0,3,1
4,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
5,Valiant 2,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
7,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
8,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1

In [7]:
data.drop_duplicates()

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,NaN,2.875,17.02,0,1,4,4
2,Datsun 710,21.0,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,22.8,6,108.0,110,3.08,3.215,19.44,1,0,3,1
4,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
5,Valiant 2,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
7,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
9,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
10,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
11,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
12,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
13,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
17,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
18,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
19,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
20,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
21,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
22,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
23,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
24,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
25,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
30,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
31,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
35,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
36,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
37,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
38,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
39,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
40,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
41,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [12]:
data.drop_duplicates(['wt','mpg','qsec'],inplace = True)

TypeError: drop_duplicates() got an unexpected keyword argument 'inplcae'

In [11]:
data.shape

(42, 12)

# sorting

In [14]:
data.sort_values(['mpg','qsec','wt'])

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
25,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
24,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
21,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
33,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
9,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
10,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
26,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
40,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
20,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
32,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
31,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
38,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
18,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
19,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
17,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
5,Valiant 2,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
8,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
14,Valiant 2,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
15,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
22,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
34,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
7,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
16,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
39,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,NaN,2.875,17.02,0,1,4,4
2,Datsun 710,21.0,4,108.0,93,3.85,2.320,18.61,1,1,4,1
41,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
30,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
4,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,22.8,6,108.0,110,3.08,3.215,19.44,1,0,3,1
36,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
35,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
37,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
12,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
28,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
11,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
27,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
13,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
29,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1

# Grouping and Aggregation

In [116]:
data = pd.read_csv('mtcars.csv')
data_g = data.groupby('am')

In [30]:
datagrouped = data.groupby('am')

In [35]:
datagrouped.mean()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,gear,carb
am,,,,,,,,,,
0,17.147368,6.947368,290.378947,160.263158,3.286316,3.768895,18.183158,0.368421,3.210526,2.736842
1,24.392308,5.076923,143.530769,126.846154,4.050000,2.411000,17.360000,0.538462,4.384615,2.923077

In [36]:
datagear = data.groupby('gear')
datagear.mean()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,carb
gear,,,,,,,,,,
3,16.106667,7.466667,326.300000,176.133333,3.132667,3.892600,17.692,0.200000,0.000000,2.666667
4,24.533333,4.666667,123.016667,89.500000,4.043333,2.616667,18.965,0.833333,0.666667,2.333333
5,21.380000,6.000000,202.480000,195.600000,3.916000,2.632600,15.640,0.200000,1.000000,4.400000

In [37]:
datagear.describe()

       mpg                                                        cyl  \
     count       mean       std   min   25%   50%     75%   max count
gear
3     15.0  16.106667  3.371618  10.4  14.5  15.5  18.400  21.5  15.0
4     12.0  24.533333  5.276764  17.8  21.0  22.8  28.075  33.9  12.0
5      5.0  21.380000  6.658979  15.0  15.8  19.7  26.000  30.4   5.0

                ...   am       carb                                          \
          mean  ...  75%  max count      mean       std  min  25%  50%  75%
gear            ...
3     7.466667  ...  0.0  0.0  15.0  2.666667  1.175139  1.0  2.0  3.0  4.0
4     4.666667  ...  1.0  1.0  12.0  2.333333  1.302678  1.0  1.0  2.0  4.0
5     6.000000  ...  1.0  1.0   5.0  4.400000  2.607681  2.0  2.0  4.0  6.0


      max
gear
3     4.0
4     4.0
5     8.0

[3 rows x 80 columns]

In [39]:
datam = data.groupby(['am','gear','cyl'])
datam.mean()

                   mpg        disp          hp      drat        wt     qsec  \
am gear cyl
0  3    4    21.500000  120.100000   97.000000  3.700000  2.465000  20.0100
        6    19.750000  241.500000  107.500000  2.920000  3.337500  19.8300
        8    15.050000  357.616667  194.166667  3.120833  4.104083  17.1425
   4    4    23.600000  143.750000   78.500000  3.805000  3.170000  21.4500
        6    18.500000  167.600000  123.000000  3.920000  3.440000  18.6000
1  4    4    28.033333   88.916667   75.166667  4.211667  2.114167  19.0000
        6    21.000000  160.000000  110.000000  3.900000  2.747500  16.7400
   5    4    28.200000  107.700000  102.000000  4.100000  1.826500  16.8000
        6    19.700000  145.000000  175.000000  3.620000  2.770000  15.5000
        8    15.400000  326.000000  299.500000  3.880000  3.370000  14.5500

              vs      carb
am gear cyl
0  3    4    1.0  1.000000
        6    1.0  1.000000
        8    0.0  3.083333
   4    4    1.0  2.000000
        6    1.0  4.000000
1  4    4    1.0  1.333333
        6    0.0  4.000000
   5    4    0.5  2.000000
        6    0.0  6.000000
        8    0.0  6.000000

In [40]:
datam.describe().to_excel('describcar.xlsx','sheet1')

In [119]:
data = pd.read_excel('Data_Train.xlsx')
data.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [95]:
data.Duration[1]

'7h 25m'

In [96]:
dur = data.Duration[1].split()

In [97]:
dur[1]

'25m'

In [98]:
int(dur[0].replace('h',''))

7

In [99]:
int(dur[1].replace('m',''))

25

In [100]:
int(dur[0].replace('h',''))*60 + int(dur[1].replace('m',''))

445

In [101]:
for i in data.Duration:
    print(i)

2h 50m
7h 25m
19h
5h 25m
4h 45m
2h 25m
15h 30m
21h 5m
25h 30m
7h 50m
13h 15m
2h 35m
2h 15m
12h 10m
2h 35m
26h 35m
4h 30m
22h 35m
23h
20h 35m
5h 10m
15h 20m
2h 50m
2h 55m
13h 20m
15h 10m
5h 45m
5h 55m
2h 50m
2h 15m
2h 15m
13h 25m
2h 50m
22h
5h 30m
10h 25m
5h 15m
2h 30m
6h 15m
11h 55m
11h 5m
8h 30m
22h 5m
2h 45m
12h
2h 50m
2h 50m
2h 15m
16h 5m
19h 55m
3h 15m
25h 20m
2h 50m
3h
2h 50m
16h 15m
15h 5m
2h 15m
6h 30m
25h 5m
12h 25m
27h 20m
10h 15m
10h 30m
2h 15m
10h 25m
2h 50m
1h 30m
13h 20m
2h 15m
1h 25m
26h 30m
7h 20m
13h 30m
5h
2h 45m
2h 50m
1h 30m
19h 5m
2h 15m
14h 50m
2h 40m
22h 10m
9h 35m
10h
21h 20m
5h 25m
18h 45m
12h 20m
18h
9h 15m
11h 5m
17h 30m
13h 20m
2h 35m
2h 25m
2h 40m
3h
1h 25m
16h 35m
12h 20m
12h 15m
7h 30m
24h
2h 45m
8h 55m
7h 10m
14h 30m
30h 20m
19h 55m
15h
2h 55m
12h 45m
10h 10m
5h 55m
15h 25m
16h 5m
10h 10m
2h 40m
11h 55m
2h 40m
1h 25m
14h 5m
20h 15m
2h 25m
23h 10m
18h 10m
16h
2h 50m
2h 20m
8h
16h 55m
3h 10m
2h 45m
14h
23h 50m
21h 40m
21h 15m
2h 45m
10h 50m
8h
8h 15m
5h 25m
8h 35m
11h 50m
27h 35m
8h 25m
20h 55m
4h 50m
8h 10m
2h 20m
24h 25m
2h 50m
12h 20m
12h 15m
23h 35m
16h 35m
2h 50m
25h 45m
26h 10m
28h 50m
2h 45m
25h 15m
9h 20m
4h 30m
15h 25m
1h 30m
2h 40m
9h 10m
2h 45m
22h 35m
3h 5m
11h 30m
9h 30m
12h 10m
17h 35m
5h 5m
25h 50m
20h
13h
18h 25m
1h 30m
9h 30m
16h
2h 20m
4h 30m
5h 45m
24h 10m
2h 35m
2h 45m
4h 55m
25h 35m
6h 20m
3h 5m
18h 40m
2h 15m
12h 10m
19h 25m
2h 50m
8h 25m
9h 15m
2h 50m
3h 15m
2h 50m
12h 20m
2h 55m
9h 35m
2h 35m
9h 30m
29h 20m
2h 55m
5h 15m
9h 5m
10h 45m
4h 55m
1h 30m
11h 40m
2h 45m
2h 55m
10h
2h 45m
10h 15m
1h 25m
9h 15m
22h 55m
28h 50m
37h 25m
2h 50m
1h 30m
1h 30m
25h 40m
2h 35m
6h 15m
17h 30m
5h 45m
2h 35m
25h 30m
13h 55m
2h 55m
10h 15m
8h 40m
5h 30m
12h
2h 15m
2h 15m
2h 50m
9h 10m
10h 25m
2h 20m
4h 30m
3h 10m
23h 30m
27h 20m
12h 35m
24h 15m
1h 20m
2h 45m
3h
11h
13h 30m
2h 50m
2h 55m
2h 45m
11h 15m
14h 35m
13h 55m
14h 5m
15h 5m
2h 15m
15h
12h 55m
9h
12h 15m
7h 40m
27h 20m
1h 25m
1h 20m
5h 30m
11h 45m
3h 15m
24h 55m
27h 20m
2h 55m
17h 5m
2h 40m
8h
3h
27h 35m
7h 30m
22h 55m
8h 35m
29h 55m
22h 15m
1h 20m
2h 40m
3h
12h 10m
2h 35m
11h 45m
2h 35m
1h 30m
2h 40m
2h 35m
22h 55m
14h 40m
15h 25m
7h 15m
20h 10m
20h 45m
2h 30m
23h 50m
27h
5h 30m
11h 50m
2h 15m
24h 30m
2h 20m
6h 30m
20h 25m
2h 35m
2h 55m
5h 35m
2h 30m
14h 45m
12h 20m
25h 30m
5h 35m
11h 45m
2h 55m
5h 40m
4h 5m
8h
2h 45m
2h 40m
2h 55m
15h 55m
23h 10m
7h 20m
2h 50m
7h 30m
3h
7h 45m
25h 20m
10h 25m
30h 20m
2h 35m
9h
15h 10m
28h 20m
3h
2h 45m
4h 55m
2h 40m
22h 10m
10h 10m
2h 50m
4h 20m
11h
3h
22h 35m
3h 5m
2h 40m
2h 50m
21h 5m
11h 50m
25h 35m
15h 25m
2h 25m
3h 40m
2h 55m
3h 10m
11h 50m
2h 50m
2h 50m
1h 30m
11h 30m
8h 50m
20h 15m
20h 10m
16h 5m
12h 35m
17h 5m
3h
15h 30m
11h 30m
2h 20m
23h 45m
1h 30m
2h 35m
24h 45m
21h 35m
5h 30m
12h 15m
8h 5m
5h
2h 50m
6h 25m
2h 20m
2h 45m
12h 45m
15h 50m
27h
26h 25m
2h 55m
24h 50m
8h 40m
25h 45m
2h 50m
6h 15m
10h 30m
26h
17h 5m
21h 20m
5h 35m
2h 50m
25h 50m
12h 10m
17h 5m
8h 30m
23h 5m
9h 20m
7h 55m
1h 30m
2h 50m
2h 15m
10h
2h 35m
7h 45m
2h 55m
26h 20m
2h 40m
11h
19h 25m
2h 55m
2h 45m
23h 15m
9h
3h 10m
6h 25m
8h 40m
2h 50m
12h 20m
5h 20m
4h
9h 45m
2h 55m
26h 20m
2h 15m
9h 45m
24h 55m
11h 55m
8h 20m
17h 25m
2h 50m
7h 5m
21h 15m
5h
2h 25m
5h 15m
15h 10m
11h 45m
3h
4h 55m
2h 45m
2h 30m
9h 45m
2h 40m
6h 30m
5h 30m
2h 40m
34h 5m
15h 25m
9h 30m
6h 5m
2h 40m
5h 50m
2h 45m
27h 20m
3h
5h 15m
16h
7h
8h 40m
9h
2h 20m
2h 20m
6h 20m
4h 25m
2h 20m
11h 5m
16h 55m
13h 45m
25h 45m
13h 55m
5h 15m
19h 15m
7h 30m
9h
24h
18h 10m
2h 55m
1h 30m
21h 20m
6h 15m
14h 30m
1h 20m
12h 55m
2h 25m
22h 30m
22h 55m
5h 25m
1h 25m
7h 15m
12h 20m
20h 10m
21h 15m
2h 15m
10h 30m
14h 5m
2h 50m
16h 25m
5h 15m
13h 50m
2h 15m
7h 15m
27h 5m
27h 35m
5h
2h 50m
2h 50m
15h 20m
5h 20m
10h 10m
27h 35m
9h 35m
28h 10m
14h
2h 35m
2h 55m
2h 35m
4h 40m
2h 30m
11h 15m
7h 55m
8h 50m
1h 25m
15h 40m
2h 35m
2h 55m
13h 25m
4h 35m
18h 30m
2h 15m
38h 15m
3h 5m
25h 50m
3h 10m
2h 50m
11h 30m
6h 35m
27h 35m
2h 35m
7h 30m
3h 15m
9h 35m
12h 30m
11h 20m
3h
2h 35m
1h 30m
26h 10m
4h 55m
2h 45m
8h 40m
7h 5m
2h 45m
24h 50m
2h 20m
11h
9h
2h 55m
3h 5m
2h 35m
13h
1h 25m
7h 35m
2h 40m
12h 55m
29h 20m
5h
8h 40m
3h
3h
2h 45m
12h 10m
2h 20m
7h 55m
29h 35m
26h 55m
12h 45m
7h 35m
2h 30m
11h 45m
23h 40m
13h 50m
12h 50m
9h 50m
2h 30m
21h 55m
26h 10m
2h 55m
20h 15m
20h 10m
10h 55m
2h 30m
21h 10m
2h 35m
20h 40m
2h 50m
6h 30m
30h
13h 10m
2h 55m
18h
8h
8h 45m
12h 30m
13h 20m
6h 10m
7h 30m
19h 15m
2h 35m
12h
3h
2h 50m
1h 25m
23h 5m
2h 50m
22h 5m
2h 15m
5h 45m
2h 50m
9h 30m
8h 55m
17h 45m
2h 50m
21h 45m
12h 35m
1h 30m
2h 15m
3h 55m
2h 45m
7h 30m
17h 20m
1h 30m
1h 30m
30h 30m
5h
11h 15m
2h 50m
19h 5m
6h 35m
7h 30m
2h 15m
2h 45m
12h 45m
2h 50m
26h 35m
12h 55m
1h 30m
8h 40m
14h
23h 30m
29h 55m
22h 10m
4h 50m
2h 45m
13h 30m
13h 20m
2h 20m
11h 55m
5h 10m
11h 45m
13h 50m
3h
6h 10m
2h 20m
10h 45m
2h 15m
2h 55m
1h 30m
7h 35m
26h 35m
4h 45m
21h 25m
8h 35m
8h 30m
2h 15m
12h 40m
8h 25m
25h 40m
2h 45m
29h 20m
2h 40m
2h 50m
2h 20m
7h 15m
20h 15m
11h 45m
2h 35m
13h 30m
1h 30m
24h 35m
20h 35m
2h 50m
4h 35m
2h 20m
11h 45m
1h 30m
12h 50m
24h 30m
11h 30m
4h
11h
5h 25m
2h 35m
5h 10m
10h 10m
26h 55m
7h 15m
8h 10m
2h 55m
5h 15m
2h 20m
1h 25m
4h 50m
2h 20m
2h 20m
13h 15m
19h 10m
22h 40m
14h 50m
15h 10m
7h 5m
1h 25m
2h 55m
8h
2h 45m
14h 55m
1h 30m
16h 15m
2h 50m
5h
22h 15m
5h 30m
8h 35m
15h 25m
21h
13h 30m
2h 50m
6h 45m
1h 30m
8h 40m
1h 30m
2h 50m
2h 35m
16h 5m
23h 50m
27h 5m
16h 15m
15h 25m
2h 50m
8h 35m
13h 50m
2h 40m
2h 25m
3h 10m
2h 55m
28h 40m
2h 50m
2h 35m
9h 40m
16h 40m
6h 20m
27h
14h 35m
12h 10m
7h 35m
2h 20m
19h 10m
20h
3h
5h 10m
2h 40m
29h 35m
4h 55m
3h
12h 30m
12h 35m
26h 20m
13h 15m
2h 50m
12h 45m
16h 20m
2h 40m
8h 15m
12h
2h 50m
11h
2h 20m
13h 50m
8h 10m
12h 10m
2h 40m
2h 45m
2h 50m
24h
3h
12h 35m
25h 50m
2h 55m
17h 5m
29h 20m
8h 55m
3h 5m
9h
10h 25m
16h 45m
2h 45m
26h 20m
13h 15m
10h 30m
7h 35m
11h
2h 50m
25h 45m
6h 25m
1h 25m
20h 10m
11h 55m
2h 50m
5h
27h
2h 50m
1h 15m
10h 15m
24h 50m
2h 50m
20h
5h 30m
2h 45m
6h 55m
2h 45m
5h 15m
6h 15m
2h 50m
19h 25m
2h 55m
11h 25m
14h 5m
2h 45m
3h 15m
14h 20m
12h 30m
5h 20m
26h 20m
3h 5m
1h 30m
7h 5m
6h 10m
8h
12h 5m
12h 55m
9h 35m
15h 10m
11h 40m
2h 55m
4h 30m
2h 40m
2h 30m
24h 10m
28h 20m
1h 25m
10h 10m
11h 30m
2h 50m
13h 45m
6h 25m
12h 55m
4h 25m
13h 30m
24h 5m
16h 5m
8h 20m
3h 40m
9h 30m
28h 15m
13h 20m
17h 50m
20h 20m
28h 5m
15h 25m
12h 5m
10h 20m
12h 25m
7h 35m
2h 50m
4h 35m
11h 15m
2h 35m
26h
2h 25m
2h 35m
14h 15m
2h 35m
22h 5m
6h 35m
8h 30m
18h 45m
35h 15m
2h 15m
2h 30m
2h 20m
2h 30m
7h 35m
35h 35m
26h 30m
11h 30m
26h 40m
3h
1h 30m
2h 55m
14h 15m
16h 55m
12h 20m
29h 35m
20h 20m
8h 25m
13h 50m
10h
19h 25m
28h
2h 50m
17h 20m
2h 45m
2h 55m
13h 25m
12h 55m
9h 45m
21h 25m
15h 40m
2h 20m
14h 25m
2h 50m
6h 35m
22h 10m
14h 25m
2h 30m
23h 35m
13h 5m
1h 30m
5h 5m
1h 20m
22h 55m
1h 30m
2h 35m
37h 20m
2h 50m
2h 50m
36h 10m
9h 15m
1h 25m
5h 5m
2h 15m
15h 10m
25h 55m
5h 40m
7h 30m
17h 45m
2h 20m
8h 15m
3h 40m
5h 55m
2h 30m
17h 30m
13h 50m
2h 15m
21h 35m
9h 30m
8h 40m
10h 25m
35h 5m
14h 15m
3h
25h 50m
2h 30m
8h 40m
10h
11h 30m
7h 30m
7h
2h 15m
7h 5m
8h
5h 25m
23h 35m
6h 35m
3h
19h 5m
2h 35m
4h 30m
1h 30m
2h 40m
26h 40m
12h 25m
14h 25m
2h 50m
3h 5m
1h 30m
8h
19h 45m
2h 45m
9h 20m
3h
26h 55m
21h 15m
2h 50m
2h 50m
16h 55m
1h 30m
25h 45m
1h 30m
9h 15m
11h 5m
6h 20m
28h 50m
27h 55m
12h 15m
22h 55m
2h 35m
2h 50m
1h 20m
26h
8h 45m
18h 10m
14h 55m
7h 30m
19h 10m
7h 15m
11h 40m
8h 40m
11h
14h 25m
4h 35m
7h 40m
11h 45m
3h
1h 30m
10h 30m
2h 35m
5h 35m
21h 15m
11h 45m
20h
5h 45m
1h 30m
2h 35m
47h
3h 15m
21h 15m
13h 20m
2h 45m
2h 55m
5h 20m
21h 20m
5h 30m
3h
2h 35m
12h 35m
26h 20m
2h 55m
6h 35m
2h 30m
23h 10m
12h 55m
26h 30m
10h 35m
1h 35m
17h 5m
1h 30m
2h 45m
28h 40m
2h 15m
1h 30m
2h 40m
7h 35m
14h 25m
25h 20m
9h 50m
16h 10m
2h 40m
5h 30m
16h 45m
2h 50m
11h 30m
9h 45m
12h 55m
10h
10h 55m
7h 40m
15h
2h 20m
1h 30m
38h 20m
2h 45m
21h 5m
2h 55m
2h 50m
25h 55m
2h 50m
1h 20m
16h 25m
2h 55m
13h
7h 20m
2h 50m
5h 15m
17h 25m
11h 45m
22h 5m
3h 10m
2h 45m
5h 20m
9h 50m
7h 5m
20h 45m
14h
6h
4h 30m
14h 50m
27h 35m
24h
17h 5m
16h 50m
2h 50m
7h 20m
6h 55m
2h 40m
26h 55m
14h 10m
2h 20m
11h 45m
1h 25m
15h 30m
19h 55m
11h
2h 50m
2h 15m
2h 45m
10h
2h 15m
6h 20m
7h 15m
5h 30m
2h 25m
1h 30m
13h 20m
2h 45m
4h 30m
5h 45m
23h 20m
16h 40m
5h
14h 25m
13h 20m
12h 30m
5h 25m
27h 35m
2h 35m
17h 40m
21h 40m
13h 20m
2h 30m
9h 35m
2h 55m
11h 35m
2h 35m
1h 25m
4h 55m
7h 30m
16h
24h 10m
3h 15m
12h 35m
12h 5m
12h 10m
7h 45m
30h 30m
7h 15m
14h 25m
2h 30m
6h 25m
15h
18h 20m
19h 55m
2h 55m
13h 15m
8h 45m
1h 30m
14h 35m
2h 50m
4h 30m
13h 25m
12h 45m
2h 30m
24h 10m
5h 25m
16h 45m
26h 25m
5h 20m
10h 25m
2h 30m
1h 30m
2h 45m
13h 30m
6h 40m
13h 25m
8h 10m
15h 30m
10h
2h 15m
3h
6h 35m
27h 20m
5h
2h 15m
2h 50m
7h 5m
14h
5h 45m
2h 40m
9h 50m
1h 25m
5h 20m
15h 30m
21h 20m
7h 15m
5h 50m
14h 35m
7h 55m
6h 35m
25h 45m
10h 30m
30h 55m
22h 55m
15h 10m
25h 20m
8h 5m
15h 40m
11h 50m
2h 40m
21h 35m
5h 20m
2h 55m
2h 50m
14h 20m
11h
12h 40m
24h 40m
2h 45m
10h 15m
11h
7h 35m
12h 30m
2h 15m
16h 15m
3h
22h
14h 25m
26h 35m
3h 10m
6h 30m
2h 50m
7h 30m
22h 55m
5h 30m
5h 55m
8h 10m
6h 40m
8h 45m
2h 45m
8h 40m
2h 35m
2h 15m
26h 55m
2h 45m
16h
16h 50m
5h 5m
10h 35m
12h
1h 15m
11h 45m
21h 10m
2h 30m
2h 25m
2h 50m
27h 20m
10h 30m
2h 55m
3h 5m
7h 30m
29h 50m
1h 20m
12h 25m
11h 50m
15h 55m
8h 10m
35h 5m
21h 35m
4h 50m
20h 20m
1h 15m
5h 10m
3h
2h 55m
7h 5m
4h 30m
1h 30m
7h 20m
1h 30m
2h 45m
18h 20m
2h 45m
2h 20m
1h 30m
23h 40m
2h 45m
2h 50m
8h 45m
7h 55m
6h 35m
23h 35m
21h 10m
2h 50m
14h 35m
37h 20m
6h 15m
26h
14h 5m
7h 30m
16h 45m
7h 40m
28h 25m
5h
8h 55m
23h 20m
14h 15m
4h 50m
2h 45m
22h 55m
5h 45m
29h 35m
2h 35m
2h 50m
17h 15m
2h 35m
8h 30m
10h
8h 15m
6h 10m
13h
3h 15m
19h 25m
8h
2h 35m
2h 30m
6h 20m
2h 15m
2h 25m
19h 55m
3h
4h 30m
12h 30m
7h 45m
2h 35m
25h 35m
6h 10m
2h 30m
9h 20m
18h 45m
5h 15m
7h 45m
14h 30m
2h 15m
19h 55m
5h 25m
16h 50m
2h 50m
4h 35m
12h 25m
9h 30m
2h 35m
2h 55m
1h 25m
2h 45m
2h 50m
5h 5m
10h 15m
8h 30m
2h 30m
4h 55m
8h 25m
4h 35m
3h 5m
10h 25m
1h 15m
13h 15m
22h 55m
5h 55m
2h 55m
2h 45m
2h 55m
2h 30m
26h 30m
25h 55m
1h 20m
2h 40m
1h 35m
2h 20m
2h 40m
4h 35m
3h 5m
15h 10m
2h 55m
9h 5m
15h 25m
4h 40m
9h 35m
4h 35m
30h 55m
2h 55m
37h 20m
26h
20h 10m
25h 20m
11h 5m
23h 50m
10h
2h 35m
20h 35m
14h 50m
2h 20m
9h 50m
7h 30m
7h 15m
22h 45m
2h 50m
20h 10m
2h 50m
22h 55m
25h 25m
5h 5m
2h 45m
12h
11h 5m
21h 50m
9h
13h 30m
8h 25m
8h 30m
10h
1h 30m
2h 20m
1h 30m
3h 5m
23h 45m
1h 30m
6h 5m
9h 20m
20h 10m
19h 45m
13h 55m
2h 15m
7h 20m
3h 10m
3h 15m
2h 50m
7h 15m
2h 55m
7h 35m
2h 55m
28h 20m
8h 40m
9h 5m
15h 20m
37h 20m
2h 55m
11h 45m
2h 50m
15h 10m
10h 15m
16h 40m
2h 20m
2h 45m
9h 5m
2h 20m
23h 50m
8h
33h 15m
14h 45m
27h 20m
2h 25m
1h 30m
7h 5m
1h 30m
4h 50m
6h 35m
10h 15m
11h 30m
21h 15m
16h 15m
25h 50m
24h 30m
2h 20m
15h 10m
14h 5m
12h 35m
10h 20m
13h 20m
2h 45m
3h
2h 50m
21h 40m
2h 40m
2h 50m
9h 10m
8h 25m
28h 25m
8h 10m
12h 30m
2h 50m
1h 30m
13h 30m
2h 20m
11h 40m
6h 35m
2h 50m
5h 15m
2h 15m
11h
37h 25m
2h 50m
21h 10m
2h 45m
6h 25m
15h 10m
7h 45m
4h 55m
5h 15m
3h 10m
22h 35m
30h 15m
5h 15m
2h 35m
21h 40m
28h 25m
12h 45m
1h 30m
14h 30m
2h 35m
25h 55m
2h 35m
9h 15m
3h 35m
9h 10m
7h 20m
14h 25m
12h 30m
27h 5m
1h 30m
13h 30m
13h 20m
12h 55m
23h 45m
27h 40m
4h 35m
3h
9h 15m
7h 20m
1h 30m
22h
2h 45m
22h 55m
4h 50m
12h 45m
8h 40m
2h 45m
16h 55m
9h 10m
8h 30m
20h 25m
8h 25m
7h 15m
9h 50m
16h 10m
13h 55m
8h
21h 15m
3h 10m
26h 35m
28h 50m
2h 45m
1h 30m
27h
4h 35m
23h 40m
2h 45m
2h 30m
3h
3h
2h 50m
2h 50m
5h 35m
3h
20h 10m
19h 5m
28h 20m
29h 55m
25h 45m
2h 15m
2h 55m
18h 10m
8h 55m
19h
2h 50m
2h 50m
2h 45m
15h 10m
29h 20m
1h 30m
2h 15m
15h 40m
24h 40m
13h 55m
2h 50m
23h 20m
9h
2h 50m
6h 10m
15h
15h 5m
1h 30m
2h 30m
12h 20m
7h 40m
14h 25m
38h 15m
12h 10m
2h 50m
9h 35m
2h 40m
6h 10m
6h 30m
25h 50m
30h 25m
3h
13h 50m
17h 30m
2h 30m
2h 35m
2h 20m
13h 15m
9h 50m
2h 55m
12h 25m
24h 35m
5h 30m
15h 10m
23h 40m
2h 35m
10h
13h 50m
14h 35m
7h 35m
13h 30m
13h 30m
8h 15m
12h 40m
14h 55m
27h 35m
14h 35m
9h 30m
15h 10m
2h 35m
3h 5m
4h 55m
4h 50m
2h 55m
1h 30m
10h 30m
12h 30m
6h
2h 50m
2h 55m
7h 35m
2h 55m
2h 35m
29h 35m
7h 30m
2h 35m
3h 15m
16h 20m
18h 50m
28h 20m
23h 15m
22h 5m
2h 35m
1h 30m
2h 35m
4h 45m
28h 50m
27h 45m
17h 5m
6h 20m
16h 5m
9h 10m
22h 45m
2h 35m
5h
15h 15m
13h 20m
17h 5m
17h 45m
5h 25m
5h 20m
14h 25m
2h 20m
15h 55m
22h 55m
2h 55m
1h 30m

15h 30m
3h
26h
2h 50m
6h 55m
23h 35m
2h 30m
10h 10m
11h 30m
27h
6h 35m
2h 50m
8h 20m
3h 5m
20h 20m
2h 20m
2h 45m
7h 35m
2h 40m
12h 55m
11h 15m
2h 30m
2h 50m
4h 50m
18h 20m
8h 55m
13h
10h 40m
13h 15m
13h 20m
2h 35m
2h 55m
12h 30m
7h 5m
6h 10m
2h 45m
2h 50m
14h 45m
5h 45m
2h 15m
8h 55m
1h 25m
33h 15m
6h 45m
23h 30m
2h 45m
26h 15m
7h 30m
1h 30m
36h 25m
28h 5m
12h 20m
6h 25m
17h 5m
1h 30m
10h 10m
8h 40m
13h 30m
17h 5m
5h 15m
5h
14h 35m
38h 15m
11h 15m
7h 20m
21h 40m
2h 40m
3h 15m
13h 30m
2h 50m
8h 40m
6h 35m
23h 45m
5h 40m
2h 55m
24h 35m
8h 40m
2h 55m
2h 50m
25h 30m
8h 15m
12h 20m
14h 5m
8h 40m
2h 45m
3h 15m
24h 35m
16h 55m
14h 35m
2h 50m
14h 5m
9h 45m
11h
10h 20m
2h 20m
23h 40m
12h 15m
5h 35m
27h 35m
3h 15m
23h 5m
9h 30m
1h 25m
2h 55m
17h 15m
22h 30m
11h 45m
2h 45m
28h 50m
29h 20m
12h
1h 25m
26h 50m
1h 30m
2h 50m
2h 30m
16h 5m
10h 55m
15h 45m
14h 25m
23h 40m
19h 40m
10h 25m
2h 35m
24h 50m
14h
9h 5m
20h
3h
22h 25m
2h 50m
9h 5m
19h 35m
26h 35m
20h 10m
1h 30m
2h 45m
26h 55m
15h 10m
2h 25m
13h
10h 30m
2h 45m
3h 15m
22h 35m
2h 55m
24h 45m
11h 55m
23h
26h 55m
7h 40m
2h 50m
8h 20m
9h 20m
2h 30m
10h 10m
9h
7h 30m
7h 40m
23h 10m
5h 30m
2h 45m
2h 55m
16h 15m
4h 30m
6h 15m
7h 5m
3h
2h 20m
24h 55m
6h 10m
12h 55m
11h 25m
13h 30m
2h 50m
16h 45m
15h 20m
6h 15m
3h
12h 15m
17h 5m
2h 35m
22h 10m
9h 30m
2h 55m
9h 50m
2h 30m
23h 15m
13h 50m
15h 10m
13h
15h
6h 35m
22h 30m
14h 40m
28h 50m
24h
11h 45m
15h 40m
13h 45m
1h 25m
2h 45m
24h 45m
15h 30m
1h 30m
1h 30m
7h 40m
4h 30m
6h 40m
26h 55m
2h 50m
20h 15m
25h 45m
2h 45m
29h 55m
10h 15m
2h 45m
2h 55m
3h
3h
10h 35m
8h 40m
7h 45m
14h 35m
4h 30m
11h 30m
19h 40m
7h 15m
9h 30m
29h 20m
10h 25m
24h 35m
27h
2h 35m
2h 20m
7h 15m
14h
2h 45m
25h 55m
1h 25m
23h 30m
2h 50m
13h 30m
28h 50m
2h 25m
26h 35m
8h
3h
1h 30m
14h 55m
1h 30m
8h
1h 30m
3h
12h
11h 5m
26h 10m
7h 55m
8h 15m
3h
2h 55m
12h 15m
4h 40m
13h 45m
15h 30m
2h 50m
6h 45m
6h 10m
12h 5m
10h 30m
21h 25m
26h 40m
21h 35m
3h 10m
11h 20m
9h 30m
16h 45m
12h 30m
9h 35m
25h
10h 15m
8h 40m
8h 40m
12h 30m
1h 30m
24h 55m
19h 45m
11h 5m
2h 30m
26h 50m
7h 35m
10h 30m
24h 40m
22h 30m
11h 35m
25h 55m
5h 20m
15h 25m
21h 15m
25h 30m
2h 20m
6h 35m
2h 50m
7h 35m
1h 30m
11h
3h
20h 25m
2h 35m
2h 50m
18h 45m
12h 35m
1h 20m
24h 35m
1h 20m
7h 15m
16h 45m
7h 25m
26h 45m
11h 45m
21h 40m
28h
8h
10h 15m
15h 10m
1h 30m
2h 55m
20h 20m
14h
7h 35m
2h 30m
14h 35m
8h 40m
9h 50m
11h 25m
2h 55m
3h
20h
28h 20m
3h 15m
8h 25m
1h 15m
12h 35m
2h 50m
6h 35m
28h 50m
1h 30m
20h
23h 50m
2h 50m
13h 30m
22h 55m
11h
22h 45m
21h 15m
14h 50m
11h
5h 5m
1h 30m
2h 20m
1h 30m
9h
3h 15m
2h 45m
6h 35m
25h 25m
7h 40m
2h 30m
13h
12h
7h 15m
2h 50m
2h 45m
2h 40m
6h 55m
6h 5m
19h 55m
7h
23h 45m
4h 50m
5h 30m
9h 5m
24h 55m
23h 50m
6h 10m
24h 15m
2h 40m
2h 25m
3h 15m
5h 30m
1h 30m
3h
13h 30m
10h 55m
12h
14h
24h 50m
12h 40m
2h 45m
1h 30m
4h 55m
30h 55m
2h 55m
1h 30m
2h 50m
7h 35m
3h 10m
2h 45m
24h 15m
4h 30m
9h 30m
22h 5m
29h 20m
7h 30m
5h
3h
1h 25m
2h 40m
2h 35m
4h 45m
7h 30m
1h 25m
23h 10m
16h 50m
1h 25m
2h 45m
3h
3h
9h
23h 10m
38h
9h 50m
6h 10m
9h 30m
12h 30m
3h 15m
4h 15m
23h 40m
3h
13h 30m
2h 20m
25h 10m
2h 30m
5h 5m
5h 40m
5h 50m
9h
2h 25m
7h 10m
18h 15m
1h 30m
24h 50m
2h 45m
4h 25m
11h 45m
7h 30m
6h 15m
1h 30m
1h 25m
2h 50m
28h 20m
2h 20m
13h 55m
5h 5m
10h 30m
12h 20m
1h 25m
16h 10m
2h 45m
18h 45m
4h 20m
5h 15m
2h 45m
9h 30m
1h 30m
10h 35m
10h 45m
9h 5m
2h 20m
8h
20h 40m
3h
13h 45m
3h 5m
5h 15m
13h 30m
8h 25m
19h 25m
13h 30m
14h 35m
20h 25m
12h 10m
15h 25m
7h 50m
15h 15m
2h 55m
6h 50m
24h 10m
23h 55m
23h 35m
14h
28h 50m
3h 10m
27h 35m
7h 30m
4h 55m
11h 35m
15h 10m
23h 55m
18h 20m
22h 5m
1h 30m
22h 15m
2h 55m
24h 10m
22h
7h 15m
5h 15m
23h 50m
5h 20m
14h 25m
8h
17h 20m
2h 55m
2h 50m
13h 55m
10h 30m
2h 50m
2h 50m
2h 50m
13h 25m
2h 45m
12h 25m
8h 15m
27h 45m
17h 55m
2h 55m
3h 40m
15h 15m
2h 45m
12h 5m
22h
12h 15m
2h 20m
10h 40m
23h 25m
6h 10m
3h
7h 35m
28h
5h 25m
7h 15m
12h 30m
9h
15h 25m
2h 35m
8h 25m
7h 15m
15h 20m
9h 50m
1h 30m
16h 45m
2h 45m
15h 20m
2h 35m
14h 30m
2h 50m
9h 10m
18h 20m
22h 55m
1h 30m
2h 45m
15h 30m
15h 20m
3h
7h 40m
10h 35m
10h 45m
10h 15m
17h 10m
12h 30m
8h
11h 5m
2h 55m
1h 30m
10h 55m
2h 30m
24h 20m
2h 55m
1h 30m
13h 15m
4h 40m
13h
16h
17h 25m
12h 10m
9h 30m
10h
1h 20m
8h
5h 55m
23h 40m
24h 55m
7h 30m
26h 55m
12h 10m
6h 40m
14h 20m
5h 35m
1h 30m
2h 50m
18h 30m
9h 20m
18h 10m
2h 55m
2h 50m
8h 50m
13h 20m
29h 50m
23h 50m
5h 55m
10h 25m
10h 40m
2h 50m
7h 20m
12h 15m
9h 30m
2h 35m
13h 20m
9h 30m
10h
10h 30m
28h 30m
5h 35m
3h 5m
24h 40m
13h 30m
5h 50m
12h 35m
19h 40m
27h 35m
4h 35m
10h 25m
2h 40m
1h 30m
6h 30m
2h 35m
12h 10m
2h 35m
11h 5m
9h 35m
2h 35m
1h 30m
11h
6h 35m
3h 15m
26h 10m
7h 40m
27h 10m
12h 30m
12h 45m
9h 40m
26h 10m
17h 35m
24h 40m
13h 10m
15h 20m
2h 35m
11h 5m
19h 20m
2h 50m
12h
23h
1h 30m
8h
2h 50m
4h 50m
2h 50m
2h 35m
3h
2h 50m
2h 20m
17h 5m
2h 50m
1h 25m
9h 50m
1h 30m
13h 20m
15h 40m
27h
3h
23h 55m
9h 50m
13h 20m
8h 45m
4h 55m
7h 45m
11h 5m
2h 35m
1h 30m
12h
2h 50m
15h 25m
13h 15m
1h 30m
22h 5m
11h 45m
7h 30m
15h 35m
11h
9h 15m
2h 30m
22h
2h 40m
14h 30m
2h 50m
2h 45m
8h
2h 55m
2h 35m
25h 30m
2h 35m
7h 30m
1h 30m
2h 15m
1h 30m
7h 20m
23h 35m
9h 35m
22h 55m
3h
5h
27h
2h 35m
20h 20m
14h 55m
19h 40m
27h 20m
5h
23h 25m
14h 5m
5h 35m
1h 30m
1h 25m
17h 20m
2h 30m
25h
20h 25m
2h 55m
1h 25m
7h 30m
22h 55m
9h 10m
14h 45m
2h 30m
12h 25m
2h 50m
10h 50m
17h 15m
2h 20m
5h 30m
11h 30m
2h 55m
10h 40m
14h 20m
2h 50m
1h 30m
10h
2h 50m
27h 20m
23h 50m
14h 35m
17h 35m
2h 45m
2h 30m
10h 25m
8h 55m
6h 5m
13h 15m
22h 30m
2h 35m
25h 30m
2h 55m
11h 55m
2h 40m
22h 30m
2h 30m
7h 40m
2h 30m
27h 5m
8h
18h 20m
6h 35m
2h 55m
11h 15m
9h 25m
26h 20m
26h 55m
24h 55m
1h 30m
10h 55m
10h 55m
2h 45m
2h 25m
8h
9h 35m
29h 20m
5h 30m
22h
2h 15m
12h 40m
37h 25m
23h 40m
22h 15m
17h 30m
3h
10h
12h 10m
9h 10m
3h 15m
12h 5m
9h 35m
14h 20m
19h 15m
15h 15m
15h 20m
21h 30m
2h 30m
2h 15m
34h 25m
1h 35m
12h 15m
12h 10m
16h 55m
22h 5m
25h 45m
7h 20m
18h 35m
12h 20m
2h 45m
15h 10m
11h 25m
26h 50m
18h 10m
7h 35m
2h 25m
21h 20m
23h 30m
2h 50m
20h
2h 35m
5h 35m
12h 20m
23h 30m
16h
25h 50m
2h 35m
11h 30m
3h 10m
12h 40m
2h 55m
2h 45m
26h 55m
2h 50m
23h 15m
4h 55m
29h 40m
5h 20m
3h
26h 20m
13h 20m
13h 30m
2h 25m
2h 35m
2h 40m
21h 10m
6h 15m
8h 5m
26h 10m
12h 45m
2h 55m
29h 35m
2h 45m
26h 5m
2h 45m
13h
2h 45m
14h 25m
2h 35m
7h 30m
2h 30m
9h 25m
2h 40m
9h 10m
8h 15m
10h 50m
11h 25m
2h 55m
29h 20m
37h 20m
10h 55m
8h 10m
20h
2h 45m
29h 5m
12h 5m
9h 50m
2h 50m
2h 20m
2h 50m
9h 10m
15h 45m
38h 15m
2h 50m
12h 30m
2h 45m
22h 55m
24h
27h
23h 50m
23h 15m
2h 35m
14h 50m
16h 50m
27h 25m
2h 35m
20h 10m
2h 50m
5h 35m
18h 20m
7h
5h 30m
18h
2h 20m
13h 15m
22h 55m
27h 20m
21h 35m
27h 35m
1h 25m
21h 55m
2h 50m
2h 20m
15h 55m
12h 20m
8h
11h 15m
3h 15m
16h 5m
26h 20m
2h 50m
6h 5m
3h 40m
7h 55m
1h 30m
5h 35m
28h 20m
19h 5m
13h 50m
25h 40m
27h 40m
2h 55m
21h 10m
5h 25m
2h 20m
7h 40m
8h 25m
2h 30m
1h 20m
19h 25m
2h 50m
3h
6h 35m
16h 35m
21h 15m
2h 55m
38h
11h 15m
22h 5m
6h 30m
1h 30m
20h 45m
1h 30m
6h 40m
5h 5m
7h 5m
11h 55m
1h 30m
14h 50m
8h 40m
27h 10m
2h 20m
2h 55m
9h 50m
2h 45m
14h 5m
12h
9h 30m
2h 50m
11h 45m
6h
11h 55m
12h 10m
2h 50m
10h 25m
12h 45m
21h 5m
9h 30m
8h 40m
9h 15m
21h 55m
23h 50m
9h
23h 15m
9h 15m
5h 35m
2h 15m
9h 30m
8h 40m
2h 45m
25h 20m
2h 50m
3h
3h
2h 45m
16h 35m
26h 20m
16h 15m
6h 5m
16h 10m
2h 25m
2h 50m
11h 30m
2h 50m
23h 40m
27h
3h 15m
11h 30m
2h 30m
2h 45m
10h
5h 15m
23h 5m
2h 50m
12h 20m
9h 45m
8h 35m
2h 45m
1h 30m
18h 25m
2h 45m
2h 30m
6h 35m
13h 30m
11h 5m
26h 10m
5h 45m
7h 35m
6h 45m
2h 45m
12h 40m
7h 15m
11h 40m
2h 15m
12h 45m
2h 50m
1h 25m
18h
2h 45m
12h 55m
15h
1h 15m
24h 40m
1h 30m
13h 30m
2h 55m
2h 25m
20h 10m
12h 10m
12h 15m
24h 30m
8h 30m
1h 30m
3h 15m
2h 35m
2h 30m
13h 20m
15h 35m
5h
2h 50m
2h 35m
12h
2h 50m
14h 20m
9h 5m
12h 25m
25h
12h 10m
12h
12h 5m
12h 45m
2h 35m
2h 25m
22h 55m
5h 10m
9h 45m
3h 5m
10h
10h 20m
26h 10m
12h 5m
23h 10m
2h 35m
17h 5m
2h 50m
16h 30m
11h 25m
10h
13h 20m
7h 30m
16h 5m
8h 20m
27h
8h 25m
2h 35m
11h 30m
2h 55m
2h 55m
2h 50m
25h 50m
1h 30m
27h 5m
24h 40m
12h 30m
26h 10m
3h 5m
3h 15m
2h 55m
21h 15m
17h 25m
21h 55m
25h 20m
14h 25m
16h 50m
3h 15m
12h 15m
1h 30m
3h
2h 55m
2h 30m
24h 45m
2h 20m
8h 25m
14h 50m
2h 35m
1h 25m
2h 35m
14h 5m
25h 15m
20h 20m
8h 20m
29h 20m
9h 45m
1h 20m
27h
15h 40m
5h 30m
7h 30m
2h 35m
19h 25m
2h 50m
14h 35m
8h 40m
15h 25m
28h 20m
1h 30m
13h 25m
23h 30m
10h 35m
1h 25m
18h 30m
24h 50m
5h 40m
1h 30m
15h
27h 20m
12h 40m
23h
2h 45m
2h 45m
2h 45m
2h 50m
6h 30m
2h 45m
2h 55m
23h 55m
25h 25m
2h 50m
14h 30m
7h 15m
22h 45m
26h 55m
2h 45m
4h 45m
10h 20m
7h 45m
7h 15m
22h 30m
7h 45m
1h 20m
2h 35m
7h 55m
12h 20m
13h
17h 45m
17h 5m
2h 40m
2h 45m
5h 35m
5h 40m
9h 30m
2h 15m
17h 5m
8h 25m
16h 35m
15h 10m
26h 5m
2h 55m
5h 30m
3h 5m
1h 30m
11h 10m
2h 30m
8h 10m
24h 55m
2h 40m
12h 10m
21h 35m
34h 25m
2h 55m
14h 55m
3h
6h 15m
23h 30m
2h 55m
10h 25m
2h 50m
4h 40m
6h 5m
2h 25m
14h 25m
2h 45m
27h 40m
10h
22h 45m
14h 20m
15h 25m
15h
16h 5m
2h 55m
15h 40m
21h 15m
1h 35m
2h 45m
6h
13h 20m
4h 55m
2h 40m
9h 30m
1h 20m
3h
24h 35m
2h 35m
12h 10m
15h 10m
2h 40m
1h 30m
24h 55m
7h 35m
18h 45m
6h 5m
11h 5m
9h 40m
13h 30m
14h 25m
6h 25m
2h 50m
5h 55m
14h 25m
13h 20m
6h 30m
22h 35m
11h
7h 45m
2h 50m
2h 20m
6h 20m
2h 30m
10h
12h 5m
2h 40m
7h 45m
17h 5m
8h 40m
2h 20m
7h 20m
18h
13h 20m
11h 45m
2h 40m
12h 30m
12h 35m
3h
10h 15m
2h 50m
7h 55m
10h 15m
15h 30m
3h 5m
2h 25m
2h 35m
11h 30m
13h 25m
2h 35m
14h 30m
23h 25m
2h 25m
5h 30m
17h 25m
7h 50m
26h 50m
16h 45m
2h 45m
28h 5m
14h 20m
9h 45m
2h 20m
14h 25m
3h 15m
3h
5h 5m
8h 5m
10h
1h 30m
20h 10m
14h 25m
26h
19h
18h 25m
15h 30m
5h 30m
9h 30m
14h 35m
21h 25m
9h 25m
14h 25m
5h 55m
1h 30m
2h 45m
20h 45m
13h 30m
28h 55m
4h 30m
29h 5m
12h 45m
5h 5m
18h 20m
22h 35m
4h 25m
9h 40m
10h
16h 50m
5h 40m
2h 50m
2h 30m
11h 30m
10h 30m
15h 20m
9h 50m
13h 20m
23h 10m
2h 20m
25h 5m
2h 35m
2h 55m
13h 10m
2h 20m
8h 35m
14h 20m
8h
2h 50m
29h 10m
1h 25m
2h 55m
5h 25m
2h 50m
2h 50m
2h 20m
8h 55m
5h 15m
11h 25m
2h 55m
2h 50m
8h 30m
3h 40m
23h 45m
13h 30m
1h 30m
26h 35m
22h 55m
34h
8h
14h 25m
15h 25m
2h 35m
9h 25m
2h 35m
2h 50m
2h 50m
28h 25m
1h 30m
25h 5m
14h 30m
22h 30m
7h 5m
1h 30m
18h 15m
7h 15m
17h 30m
8h 55m
2h 50m
20h 35m
20h
8h 10m
17h 5m
9h 15m
2h 25m
8h 25m
13h 30m
2h 50m
6h
18h 25m
14h 5m
22h 30m
25h 30m
1h 30m
2h 25m
15h 35m
2h 20m
26h 15m
3h 5m
2h 35m
13h
18h 45m
3h
11h 25m
11h 45m
1h 30m
22h 5m
27h 45m
15h 40m
2h 30m
24h 35m
1h 30m
5h 10m
5h 25m
13h 20m
8h 35m
1h 25m
3h
10h 30m
3h
2h 30m
12h 5m
22h 10m
22h 10m
3h 15m
6h 20m
24h 30m
4h 15m
6h 35m
14h 50m
2h 50m
8h 25m
2h 35m
12h
18h 45m
25h 25m
8h 30m
2h 55m
20h
24h 45m
8h 40m
6h 5m
10h 55m
14h 5m
18h 50m
2h 30m
7h 40m
7h 15m
3h 5m
10h 25m
2h 50m
9h 10m
11h 40m
13h 50m
2h 15m
2h 30m
5h 40m
16h 15m
2h 55m
2h 45m
9h
14h 25m
15h 20m
9h 30m
2h 30m
25h 50m
30h 20m
2h 55m
1h 30m
15h 40m
20h 25m
22h 5m
3h 5m
20h 15m
21h 40m
7h 35m
6h 35m
3h
23h 40m
1h 30m
9h 5m
5h 25m
9h 5m
1h 30m
21h 10m
2h 30m
24h 45m
2h 45m
16h
21h 40m
2h 45m
7h 5m
15h 5m
7h 20m
2h 40m
2h 35m
25h 45m
2h 20m
2h 25m
2h 45m
27h 45m
16h 15m
2h 35m
28h 50m
9h 50m
5h 15m
25h 45m
21h 20m
2h 20m
17h 5m
10h 55m
9h 10m
16h 35m
22h 5m
2h 45m
2h 40m
8h 10m
26h
12h 55m
1h 25m
2h 55m
10h 55m
2h 30m
9h 25m
13h
29h 20m
11h
2h 55m
11h 20m
8h 20m
27h 20m
30h 40m
25h 15m
8h 35m
15h 10m
2h 20m
1h 30m
15h 5m
7h 40m
29h 5m
12h 15m
23h 50m
28h 50m
7h 35m
10h 30m
2h 50m
21h 25m
16h 5m
3h
13h 45m
9h 20m
27h 20m
12h
2h 55m
12h 15m
2h 55m
24h
2h 45m
2h 55m
4h 55m
7h 20m
4h 55m
23h 35m
7h 15m
1h 30m
2h 30m
4h 35m
16h 20m
2h 50m
28h 55m
15h 5m
3h
2h 55m
27h 10m
2h 45m
1h 25m
5h 45m
12h 15m
3h 35m
7h 30m
15h 25m
25h 20m
2h 50m
4h 50m
16h 55m
15h 25m
10h 25m
6h 15m
8h
7h 5m
1h 30m
5h 55m
9h 30m
8h 40m
18h 20m
19h 40m
22h 10m
12h 45m
23h 15m
11h
2h 55m
1h 30m
15h 25m
2h 15m
2h 35m
2h 45m
21h 30m
22h 55m
18h 10m
2h 20m
14h 5m
2h 45m
25h 50m
2h 30m
2h 30m
2h 50m
14h 30m
8h 55m
2h 40m
2h 25m
2h 50m
6h 25m
10h 20m
15h 40m
11h 25m
15h 10m
23h 35m
2h 20m
2h 40m
20h 20m
8h 30m
2h 15m
6h 15m
26h 50m
30h 45m
5h
27h 20m
6h 25m
2h 45m
2h 50m
5h 15m
22h 55m
14h 45m
16h 45m
18h 25m
16h 35m
2h 35m
7h 50m
12h 40m
1h 25m
19h 45m
16h 55m
2h 50m
14h 15m
27h 35m
1h 30m
22h 55m
12h 20m
2h 45m
8h 40m
2h 35m
22h 5m
24h
36h 10m
14h
16h 50m
27h 5m
7h 15m
20h 55m
5h
7h
2h 30m
5h 15m
10h 50m
5h 15m
20h 55m
8h 40m
2h 15m
12h
6h 15m
8h 40m
14h 10m
32h 55m
2h 50m
6h 25m
2h 30m
2h 30m
10h 40m
19h 55m
8h 40m
11h
10h 5m
4h 55m
30h 55m
11h 25m
26h 35m
3h 5m
14h 35m
2h 25m
4h 50m
3h
11h 30m
35h 20m
2h 40m
28h 50m
2h 35m
2h 55m
17h 25m
14h 50m
10h 30m
5h 35m
1h 30m
2h 30m
8h 55m
1h 30m
4h 30m
12h 15m
9h 30m
14h 25m
27h 20m
26h 55m
13h 30m
12h 5m
2h 30m
22h 55m
15h 40m
5h
14h 5m
2h 55m
23h 15m
21h 15m
2h 55m
2h 55m
25h 50m
5h 25m
3h
3h
2h 40m
17h 20m
3h 10m
8h 30m
12h 5m
8h 20m
15h
13h 10m
8h 30m
26h 55m
1h 30m
25h
2h 55m
9h
26h 20m
1h 20m
13h 30m
9h 30m
2h 30m
1h 30m
17h 45m
11h 25m
23h 35m
2h 50m
2h 55m
2h 25m
3h 15m
5h 55m
6h 10m
18h 20m
26h 10m
21h 35m
21h 15m
23h 20m
5h 30m
3h 15m
5h 55m
13h 25m
2h 35m
26h 35m
13h 15m
2h 15m
2h 30m
2h 35m
7h 40m
2h 40m
1h 30m
2h 35m
23h 30m
6h 10m
5h 30m
1h 30m
3h 10m
13h 55m
2h 50m
7h 35m
7h 55m
2h 25m
1h 30m
9h
14h 35m
11h 15m
3h
2h 35m
23h 40m
4h 40m
21h 15m
23h 5m
2h 55m
8h 45m
19h 55m
2h 45m
12h 35m
2h 45m
16h 10m
30h 30m
4h 40m
27h 35m
12h 45m
11h 5m
3h
11h 30m
2h 50m
20h
10h 10m
2h 30m
13h 10m
2h 45m
6h 40m
27h
23h 45m
5h 20m
12h 30m
27h 35m
7h 35m
11h 45m
13h 30m
3h
27h 40m
7h 30m
9h 30m
13h 30m
3h 5m
20h 10m
10h 15m
9h 15m
14h 25m
8h 25m
14h 50m
2h 40m
8h 30m
2h 50m
2h 45m
23h 15m
16h 50m
2h 30m
1h 25m
6h 35m
14h 25m
12h 25m
2h 20m
1h 30m
10h 40m
1h 30m
27h 10m
12h 25m
8h 50m
2h 50m
24h
20h 55m
6h 5m
12h 15m
2h 30m
2h 35m
12h 30m
12h 35m
16h 5m
21h 15m
2h 20m
2h 30m
12h 15m
23h 50m
2h 50m
23h 10m
8h 5m
10h 40m
2h 30m
7h 15m
1h 30m
10h 30m
23h 15m
2h 30m
5h
25h 5m
9h 45m
2h 25m
15h 25m
13h 30m
20h 15m
15h 30m
15h
21h 30m
7h 5m
2h 55m
28h 20m
2h 30m
18h 10m
21h 15m
11h 5m
10h 40m
10h
4h 50m
5h 30m
13h 20m
9h 30m
26h 45m
9h 15m
1h 15m
7h 35m
1h 30m
2h 50m
5h 10m
1h 30m
2h 55m
16h 45m
2h 20m
19h 55m
3h 5m
2h 55m
2h 55m
26h
2h 55m
15h 25m
11h 5m
1h 30m
16h 15m
6h 20m
26h 55m
20h 45m
24h 45m
5h 45m
9h 45m
2h 40m
5h 35m
2h 45m
3h
2h 35m
24h 35m
2h 35m
2h 40m
20h 20m
2h 35m
3h
6h 15m
2h 20m
2h 20m
10h 40m
8h 30m
1h 30m
15h 50m
2h 30m
12h
1h 30m
21h 35m
2h 45m
26h 15m
2h 50m
1h 25m
3h
2h 30m
7h 30m
2h 20m
10h 30m
2h 50m
2h 45m
14h
2h 50m
1h 30m
27h 35m
6h 35m
11h 40m
2h 55m
11h 50m
9h 50m
26h 50m
2h 45m
4h 55m
2h 45m
13h 10m
27h 10m
2h 45m
15h 50m
8h 25m
2h 20m
14h 5m
2h 50m
16h 20m
25h 10m
2h 50m
38h 20m
11h 5m
2h 55m
19h 55m
15h 45m
9h 15m
2h 35m
4h 55m
13h 15m
26h
18h 30m
9h
27h 35m
19h 15m
11h 45m
22h 55m
8h 10m
6h 55m
12h 45m
2h 35m
2h 50m
10h 15m
3h
12h 30m
4h 50m
38h
13h 20m
12h 45m
26h 35m
16h 40m
2h 50m
4h 15m
2h 45m
1h 30m
2h 35m
7h 30m
29h 20m
23h
2h 45m
12h 10m
7h 5m
2h 40m
15h 40m
7h 45m
5h 45m
2h 30m
10h 10m
12h 10m
1h 30m
2h 50m
12h 15m
1h 30m
9h 10m
22h 5m
10h
6h 15m
2h 55m
2h 35m
9h 50m
23h 50m
5h 45m
8h 15m
10h 25m
14h 15m
13h 20m
2h 45m
34h
7h 5m
8h 55m
15h 30m
11h 50m
1h 30m
9h 15m
15h 30m
3h
7h 30m
2h 35m
2h 35m
14h 30m
6h 15m
10h 30m
2h 50m
7h 5m
13h 10m
13h 15m
7h 15m
26h
11h
24h 45m
2h 35m
27h 35m
14h 25m
20h 10m
2h 45m
12h 20m
2h 15m
8h 50m
26h 10m
2h 45m
1h 25m
10h
1h 30m
5h 15m
2h 50m
20h 20m
6h 35m
12h 35m
2h 35m
2h 20m
11h 45m
2h 50m
2h 20m
1h 30m
2h 20m
1h 30m
22h 5m
7h 15m
9h 15m
27h 10m
12h 45m
4h 30m
2h 55m
14h 30m
12h 10m
22h 25m
9h 10m
10h
1h 30m
2h 30m
5h 30m
12h 45m
15h 10m
23h 20m
2h 20m
8h
11h 15m
19h
10h
2h 35m
5h 15m
8h 5m
2h 15m
11h 30m
33h 15m
1h 30m
13h 5m
2h 55m
2h 55m
2h 35m
22h 55m
21h 5m
5h 10m
13h 30m
12h 15m
2h 40m
19h 35m
28h 50m
2h 35m
18h 20m
24h 10m
2h 50m
26h 50m
2h 15m
2h 55m
24h 30m
14h 10m
22h 45m
16h 35m
5h 20m
8h 30m
9h 50m
8h 40m
21h 40m
7h 30m
13h 45m
1h 30m
38h 15m
1h 30m
16h 5m
15h 10m
20h 10m
10h 55m
5h 40m
2h 45m
2h 45m
18h 20m
13h 50m
7h 35m
23h 15m
13h 20m
23h 20m
19h 25m
13h 30m
2h 30m
23h 15m
2h 20m
1h 15m
3h 10m
11h 30m
4h 50m
22h
20h 15m
11h 15m
12h 45m
12h 30m
11h 30m
17h 15m
5h
1h 30m
7h 35m
2h 55m
7h 25m
5h 55m
15h 45m
11h 30m
9h 45m
12h 30m
5h
22h
22h 5m
16h 55m
1h 25m
2h 45m
10h
1h 20m
14h 25m
18h
4h 55m
7h 30m
7h 55m
2h 30m
9h 45m
2h 45m
7h 5m
9h 30m
1h 30m
15h
17h 5m
24h 20m
12h 30m
24h 40m
3h 5m
2h 25m
2h 45m
7h 30m
1h 30m
4h 55m
2h 45m
8h 40m
28h 50m
7h 15m
20h 15m
2h 50m
12h 45m
30h 40m
4h 5m
10h 15m
38h 15m
21h 35m
15h 25m
2h 20m
5h 20m
2h 50m
22h 45m
2h 50m
25h 50m
6h 30m
2h 25m
14h 35m
2h 55m
12h 40m
2h 15m
9h 35m
17h 20m
11h 50m
2h 55m
1h 25m
16h 55m
2h 20m
2h 55m
9h 30m
2h 40m
7h 15m
4h 55m
19h 10m
10h 45m
22h 15m
13h 20m
10h 35m
7h 15m
18h 25m
15h 40m
7h 35m
2h 40m
16h 45m
5h 35m
11h
2h 45m
7h 55m
9h 30m
5h 45m
29h 20m
1h 30m
7h 5m
4h 40m
1h 25m
26h 55m
26h 30m
1h 30m
2h 45m
3h
3h
2h 50m
30h 30m
2h 50m
20h 45m
22h 30m
2h 50m
26h
16h 25m
9h 20m
7h 5m
24h 35m
2h 20m
22h 10m
7h 35m
26h
16h 5m
38h
13h 15m
10h 40m
2h 50m
16h 10m
13h 20m
6h 30m
1h 30m
10h 25m
12h 45m
32h 5m
8h 15m
3h
18h 45m
29h 20m
31h 40m
2h 50m
2h 55m
28h 50m
1h 15m
18h 20m
12h 15m
2h 25m
3h
33h 15m
2h 50m
14h
7h 50m
7h 35m
21h 15m
2h 50m
2h 40m
25h 5m
7h 35m
7h 30m
9h 15m
2h 35m
1h 30m
8h
2h 30m
15h 20m
5h 50m
2h 25m
26h 10m
2h 40m
21h 20m
2h 50m
3h
4h 50m
7h 45m
10h 45m
3h
9h 50m
10h
6h 55m
18h 30m
2h 40m
20h 10m
2h 25m
23h 15m
11h 15m
5h 30m
10h 15m
22h 55m
1h 30m
9h
16h 20m
12h 15m
6h 20m
7h 20m
1h 30m
15h 15m
1h 20m
5h 30m
9h 35m
8h 55m
2h 50m
12h 20m
23h 50m
16h 55m
2h 55m
16h 5m
23h 15m
14h 25m
1h 30m
13h 20m
3h 5m
28h 50m
14h 40m
2h 45m
5h 50m
9h 5m
1h 30m
23h 30m
8h 40m
14h 20m
2h 15m
2h 45m
5h 20m
3h
5h 20m
2h 50m
2h 15m
2h 55m
8h
25h 40m
23h 45m
22h 35m
8h 40m
23h 40m
7h 50m
4h 50m
2h 55m
30h 40m
14h 55m
27h 20m
23h 35m
9h
20h 55m
20h 10m
14h 25m
7h 35m
7h

2h 55m
1h 30m
1h 25m
9h 50m
7h 20m
14h 30m
9h 50m
2h 35m
8h
2h 30m
5h 20m
2h 25m
14h 55m
25h 45m
23h 50m
10h 30m
2h 55m
6h 15m
16h 10m
23h
23h 20m
7h 30m
1h 30m
14h
7h 5m
2h 55m
12h 15m
2h 45m
20h 15m
27h 5m
20h 15m
2h 45m
11h 45m
1h 25m
2h 45m
3h
11h
24h 55m
26h 35m
23h 40m
23h 35m
25h 45m
2h 45m
1h 25m
19h 15m
15h 30m
24h 30m
13h 20m
7h 35m
2h 45m
2h 50m
10h 10m
30h 30m
2h 50m
8h 25m
1h 30m
12h 25m
24h 55m
2h 35m
21h 15m
22h 55m
2h 35m
3h
8h 55m
22h 30m
1h 30m
9h 5m
21h 25m
2h 40m
13h 30m
6h 25m
20h 55m
10h 10m
26h 30m
10h 15m
7h 20m
10h 45m
7h 5m
2h 20m
12h
20h 20m
11h
13h 50m
9h
7h 50m
16h 5m
9h
12h 40m
3h 5m
1h 30m
11h 15m
12h 25m
12h 20m
2h 25m
15h 35m
2h 50m
5h 5m
6h 35m
7h 5m
2h 50m
13h 30m
2h 50m
3h
33h 15m
23h 10m
2h 55m
6h 30m
2h 30m
2h 55m
10h 45m
23h 40m
2h 35m
9h
1h 30m
1h 35m
11h 45m
2h 55m
15h 30m
27h 35m
2h 50m
5h 15m
14h 35m
2h 40m
7h 30m
2h 50m
1h 30m
6h 35m
2h 35m
11h 40m
2h 50m
2h 45m
5h
7h 15m
8h 35m
3h
17h 5m
11h
3h 10m
5h 20m
9h
6h 30m
15h 25m
2h 45m
6h 30m
16h 5m
12h 15m
25h 30m
12h 35m
27h 45m
6h 15m
2h 55m
6h 10m
2h 40m
7h 30m
5h 20m
22h 25m
26h 30m
3h
2h 40m
7h 45m
25h 5m
9h 20m
3h 5m
9h 45m
25h 35m
2h 40m
5h 15m
24h 55m
1h 30m
2h 50m
2h 15m
26h 55m
2h 15m
24h 30m
10h 15m
5h 25m
10h 20m
7h 5m
3h
23h 5m
24h 50m
12h 45m
22h 10m
8h 10m
2h 30m
9h 20m
6h 5m
24h 35m
3h
11h 15m
8h 25m
2h 40m
20h 20m
1h 30m
30h 20m
15h 30m
2h 45m
7h
3h 5m
7h 35m
2h 50m
13h 55m
23h 45m
2h 45m
10h 15m
10h 5m
12h 45m
2h 35m
2h 50m
14h 45m
7h 20m
23h 10m
2h 20m
5h 30m
13h 45m
2h 20m
1h 30m
2h 20m
2h 55m
12h 45m
2h 20m
24h 45m
38h
4h 55m
11h 45m
11h 45m
3h 10m
2h 50m
2h 35m
6h 35m
1h 20m
2h 15m
23h 40m
5h
2h 40m
23h 40m
12h 10m
7h 35m
29h 20m
2h 55m
13h 20m
12h 25m
1h 20m
28h 15m
5h 20m
1h 20m
7h 5m
1h 30m
23h 20m
2h 50m
11h 30m
2h 45m
2h 35m
7h 5m
3h 15m
2h 45m
14h 30m
28h 20m
2h 50m
2h 30m
9h 50m
6h 20m
7h
2h 35m
2h 40m
8h 40m
2h 40m
10h 25m
2h 25m
13h 55m
2h 35m
2h 30m
2h 30m
25h 20m
13h
5h 10m
13h 20m
4h 55m
10h 35m
18h 20m
16h 5m
7h 30m
25h 5m
11h
14h 35m
1h 25m
19h 55m
2h 25m
2h 55m
5h 40m
12h 10m
11h 45m
10h 15m
1h 30m
11h 35m
2h 20m
7h 20m
6h 25m
3h
11h
14h 30m
12h 20m
13h 15m
11h
2h 45m
25h 30m
12h
15h 25m
1h 25m
7h 15m
2h 35m
16h 35m
2h 55m
1h 30m
10h 45m
7h 45m
4h 45m
12h 15m
19h 25m
2h 35m
27h 20m
2h 20m
10h 30m
25h 5m
11h 15m
24h 50m
19h 50m
2h 15m
5h 10m
29h 5m
26h
9h 30m
2h 35m
2h 15m
15h 55m
2h 15m
16h 5m
23h 50m
4h 50m
16h 45m
2h 20m
15h
14h 5m
13h 20m
12h 30m
7h 15m
3h 5m
2h 50m
2h 55m
2h 35m
27h 35m
1h 20m
19h 55m
3h
1h 30m
14h 45m
8h 35m
19h 25m
26h 35m
5h
4h 50m
7h 20m
27h 45m
3h
2h 50m
2h 45m
8h 35m
3h
8h 5m
2h 50m
8h 30m
11h 5m
4h 30m
2h 50m
33h 45m
2h 50m
24h 45m
30h 10m
27h 5m
15h 20m
26h 10m
21h 15m
1h 30m
17h 25m
16h 45m
3h 15m
10h 20m
10h 20m
2h 35m
2h 55m
9h 35m
7h 15m
8h 55m
2h 55m
14h 5m
18h 45m
2h 35m
2h 45m
14h 10m
1h 30m
2h 35m
2h 55m
7h 20m
11h 50m
1h 20m
7h 30m
9h 20m
24h 50m
21h 15m
24h 50m
18h 20m
2h 20m
7h 25m
2h 50m
38h
1h 25m
2h 40m
3h 5m
29h 55m
2h 30m
8h
14h 35m
5h 15m
1h 30m
2h 45m
2h 55m
15h 55m
2h 55m
8h 25m
7h
2h 50m
21h 45m
3h 5m
11h 5m
4h 55m
23h 35m
5h 15m
22h 55m
3h 15m
21h 20m
7h 30m
1h 25m
28h 50m
10h 20m
16h 40m
7h 5m
7h 20m
2h 55m
24h 35m
24h 50m
7h 35m
11h
16h 15m
14h 50m
9h 50m
13h 20m
8h 25m
27h 35m
1h 30m
2h 50m
13h 15m
25h 55m
2h 35m
22h 15m
13h 40m
10h 25m
2h 50m
15h 25m
2h 50m
22h
8h 25m
25h 55m
9h 30m
12h
9h 45m
23h 45m
3h 15m
15h
21h 25m
8h 35m
25h 20m
21h
17h 35m
1h 30m
10h 50m
23h 45m
11h 25m
2h 30m
6h 35m
2h 40m
2h 25m
13h 10m
26h 35m
1h 25m
15h 30m
14h 15m
22h
10h 25m
10h 25m
14h 25m
27h
8h 35m
8h
12h 20m
26h 35m
3h 10m
23h 50m
25h 15m
2h 20m
28h 25m
21h 30m
12h 10m
2h 50m
22h 35m
6h 15m
2h 30m
10h 55m
13h 10m
11h 45m
9h 25m
14h 15m
12h 25m
13h 30m
20h 20m
8h 10m
16h 45m
1h 30m
2h 30m
12h 10m
6h 55m
12h 40m
3h 40m
2h 40m
21h 55m
9h 50m
2h 35m
2h 45m
1h 25m
11h 45m
6h 30m
12h 5m
16h 15m
15h 10m
19h 30m
35h 5m
29h 50m
9h 40m
11h 15m
5h 45m
21h 45m
8h 55m
13h 25m
5h 30m
2h 50m
3h
9h 30m
2h 45m
24h 30m
2h 50m
2h 55m
19h 5m
2h 50m
2h 30m
7h 55m
2h 50m
1h 15m
7h 45m
3h
2h 45m
19h 25m
24h 10m
4h 55m
25h
2h 15m
14h 10m
8h
7h 50m
2h 45m
2h 30m
16h 15m
15h 40m
18h 20m
16h 15m
19h 5m
9h 30m
5h
19h 15m
27h 35m
14h 35m
4h 40m
13h 25m
7h 35m
14h
2h 45m
18h 25m
21h 25m
6h 35m
11h
1h 30m
5h 20m
3h
28h 5m
2h 40m
2h 15m
1h 15m
24h 15m
9h 20m
2h 40m
3h
3h
2h 45m
5h 45m
15h
23h 50m
2h 50m
16h 5m
9h 5m
23h 15m
21h 15m
11h 5m
22h
2h 45m
31h 30m
1h 25m
19h 55m
5h 5m
6h 15m
5h 55m
2h 55m
21h 35m
15h 10m
25h 30m
17h 5m
2h 35m
25h 40m
5h 45m
3h 5m
9h 5m
8h
5h 50m
13h 25m
2h 20m
9h 30m
27h 10m
2h 40m
20h 10m
21h 10m
2h 50m
24h
15h 15m
10h 30m
4h 50m
6h 5m
2h 55m
21h 35m
9h 20m
27h 20m
2h 35m
5h 15m
4h 35m
7h 30m
2h 45m
24h 30m
7h 15m
11h 55m
8h 10m
15h 40m
10h 30m
1h 25m
10h 35m
4h 55m
21h 45m
24h 5m
2h 35m
2h 35m
10h 55m
6h 20m
7h 30m
2h 45m
22h 55m
2h 50m
2h 55m
2h 45m
3h
11h 40m
26h 15m
27h
11h 5m
25h 45m
1h 25m
21h 25m
1h 25m
12h 20m
5h 30m
20h 35m
9h 15m
6h 30m
2h 55m
13h 50m
22h 45m
14h 35m
3h 5m
2h 20m
6h 55m
19h 55m
18h 45m
2h 50m
13h 25m
2h 55m
2h 55m
2h 45m
5h 45m
14h 45m
2h 20m
18h 20m
13h
2h 45m
8h
29h 5m
10h 10m
2h 35m
15h 40m
13h 20m
2h 50m
25h 45m
2h 20m
13h
4h 25m
2h 50m
22h 10m
4h 30m
13h 20m
20h 20m
3h 15m
2h 35m
2h 35m
4h 50m
10h
2h 50m
11h 45m
2h 35m
2h 40m
22h 10m
25h 15m
8h 55m
6h 25m
3h
19h 25m
28h 5m
2h 50m
2h 50m
25h 5m
21h 35m
21h 35m
13h
7h 15m
15h 55m
7h 35m
13h 20m
2h 50m
7h
12h 30m
10h 50m
1h 30m
2h 35m
2h 45m
5h 40m
2h 55m
12h 25m
2h 20m
1h 20m
20h 15m
11h 35m
27h 45m
26h 10m
5h 5m
2h 55m
23h 35m
24h 10m
3h
7h
21h 35m
10h 25m
15h 55m
28h 20m
2h 50m
7h 20m
2h 25m
2h 35m
3h 5m
1h 30m
2h 20m
8h 40m
30h
3h
25h 40m
2h 55m
2h 55m
20h 10m
6h 25m
2h 50m
27h 45m
2h 45m
13h 25m
3h 40m
18h 20m
2h 25m
11h 25m
21h 40m
30h 30m
11h
7h 30m
22h 40m
1h 30m
2h 45m
13h 15m
13h 55m
9h 30m
30h 20m
1h 15m
34h 30m
3h 5m
13h 45m
23h
1h 25m
14h 55m
16h 45m
26h 50m
13h 20m
8h
8h
21h 20m
18h 20m
2h 40m
9h 35m
15h 10m
9h 50m
20h 25m
23h 50m
10h 35m
13h 20m
14h 15m
14h 20m
24h 35m
3h
1h 20m
8h
2h 55m
5h 5m
7h 20m
6h 30m
21h 45m
13h 20m
18h 25m
22h
25h 30m
17h 25m
2h 20m
1h 30m
15h 30m
14h 25m
2h 55m
14h 35m
4h 55m
7h 35m
9h 50m
14h 40m
8h 30m
2h 50m
14h 35m
2h 35m
2h 55m
9h 35m
13h
25h 55m
25h 35m
2h 15m
24h 30m
1h 25m
10h
2h 50m
2h 50m
1h 30m
12h
1h 30m
21h 20m
1h 30m
12h 35m
16h 45m
13h
28h
2h 50m
17h 10m
9h 30m
10h 20m
7h 55m
14h
2h 20m
14h 25m
2h 35m
23h 30m
16h 40m
2h 45m
2h 50m
26h 35m
12h 15m
10h 20m
15h 25m
9h
2h 50m
11h 20m
2h 55m
7h 40m
11h
2h 35m
5h 50m
3h 10m
25h 35m
6h 15m
2h 15m
14h 5m
2h 55m
8h 20m
19h 55m
21h 25m
4h 55m
3h
3h
2h 55m
5h 15m
23h
18h 20m
2h 50m
2h 55m
9h 30m
1h 25m
7h 45m
12h 55m
2h 40m
2h 35m
2h 50m
15h 20m
2h 55m
9h
20h 25m
13h
2h 50m
15h 55m
12h 45m
19h 25m
6h 40m
24h 10m
10h 20m
2h 55m
11h 5m
19h 30m
8h 20m
7h 5m
24h 40m
3h 40m
23h
14h 5m
7h 20m
1h 25m
7h 30m
2h 20m
16h
2h 35m
12h 10m
1h 30m
3h 5m
8h 5m
2h 55m
21h 20m
11h 45m
1h 30m
3h
4h 40m
15h 20m
2h 40m
21h 35m
25h 25m
2h 30m
1h 25m
8h 40m
19h 55m
17h 5m
1h 30m
14h 25m
26h 10m
2h 30m
10h 15m
6h 25m
11h 15m
2h 35m
27h 45m
7h 35m
10h 40m
1h 25m
2h 55m
1h 20m
2h 50m
2h 45m
5h 15m
8h 45m
18h 45m
14h 20m
1h 30m
2h 30m
26h 35m
9h 30m
7h 30m
20h 10m
5h 30m
12h 45m
2h 20m
8h 40m
7h 5m
14h 50m
19h 40m
1h 30m
13h 55m
3h 5m
5h 20m
2h 35m
14h 25m
5h
14h 5m
9h
2h 20m
2h 20m
1h 30m
2h 50m
11h 5m
11h 25m
2h 40m
11h 45m
2h 20m
9h
22h 30m
10h 35m
11h 45m
2h 20m
1h 20m
7h 15m
21h 35m
9h 5m
11h 15m
23h 20m
2h 35m
13h 30m
8h 10m
7h 15m
2h 50m
19h 25m
21h 25m
12h 20m
2h 25m
28h 15m
2h 50m
2h 55m
2h 25m
20h 55m
6h
8h 20m
3h
9h 20m
2h 40m
4h 15m
18h 35m
8h 40m
2h 55m
24h 45m
24h 45m
2h 20m
1h 30m
2h 35m
23h
15h 30m
2h 15m
3h 5m
2h 50m
20h
17h 5m
12h 45m
24h 10m
1h 30m
26h 50m
12h 25m
9h 30m
6h 25m
1h 30m
16h 15m
24h 45m
6h 20m
21h 40m
5h 15m
27h
19h 40m
14h 35m
3h 40m
2h 50m
7h 5m
2h 55m
10h
33h 15m
7h 45m
2h 45m
1h 20m
12h 45m
4h 30m
8h 40m
1h 20m
1h 25m
17h 20m
12h 10m
13h 30m
1h 30m
22h
25h
2h 15m
1h 30m
23h 30m
13h 50m
13h 30m
2h 35m
11h 30m
3h
2h 55m
2h 45m
9h 45m
6h 40m
10h 55m
2h 15m
27h 10m
7h 15m
8h 20m
15h 40m
13h 45m
21h 25m
1h 30m
7h
6h 10m
14h 55m
1h 30m
19h 30m
2h 55m
1h 30m
2h 55m
12h 40m
19h 55m
2h 35m
21h 35m
5h 30m
25h 30m
26h 20m
9h 10m
8h 10m
2h 25m
8h 10m
2h 30m
23h 30m
10h 40m
2h 55m
9h 50m
2h 15m
28h 5m
17h 50m
16h 30m
25h 45m
22h 45m
2h 50m
11h 45m
1h 30m
16h 45m
9h 5m
5h 30m
7h 15m
17h 25m
13h 30m
6h 30m
2h 50m
2h 55m
2h 50m
2h 20m
2h 30m
12h 10m
8h 30m
2h 50m
2h 45m
3h
16h
2h 35m
2h 25m
23h 35m
22h 55m
2h 15m
3h 15m
6h 5m
5h 5m
2h 20m
26h 35m
1h 30m
2h 45m
2h 50m
11h 25m
18h 50m
2h 35m
14h 20m
2h 45m
12h 10m
5h
11h
2h 20m
3h
19h 40m
9h 30m
2h 30m
2h 50m
2h 20m
2h 45m
16h 55m
4h 30m
25h 20m
22h
22h 45m
9h 20m
2h 55m
2h 45m
2h 40m
2h 35m
21h 10m
8h 20m
23h 30m
16h 55m
5h 30m
2h 25m
24h 55m
2h 55m
27h 5m
11h 45m
2h 50m
21h 15m
5h 20m
5h 45m
11h 15m
12h 55m
21h 15m
9h 30m
12h 30m
6h 35m
3h
14h 10m
2h 35m
2h 35m
14h 40m
7h 45m
2h 50m
13h 30m
1h 25m
25h 45m
21h 35m
11h
7h 30m
3h 15m
2h 35m
5h 50m
2h 20m
22h 55m
11h 40m
2h 35m
2h 25m
24h
3h
10h 35m
36h 10m
2h 25m
2h 35m
11h 30m
2h 55m
2h 50m
8h 55m
5h 15m
12h 15m
26h 40m
8h 55m
1h 20m
23h 5m
2h 15m
8h 40m
2h 30m
5h 5m
16h 55m
15h 15m
18h 45m
20h 55m
10h
10h 15m
5h 40m
28h 20m
6h 30m
15h 55m
10h 40m
26h 35m
25h 45m
5h 55m
19h 45m
9h 15m
2h 40m
11h 5m
10h 15m
2h 30m
7h 30m
6h 10m
8h 30m
2h 45m
2h 35m
4h 55m
9h 20m
12h 45m
24h 50m
9h 20m
2h 55m
2h 30m
17h 55m
2h 50m
2h 30m
3h
16h 50m
1h 30m
6h
2h 45m
14h 15m
11h 5m
2h 40m
20h 10m
24h 55m
3h
9h 50m
12h 30m
2h 50m
9h 35m
12h
2h 15m
2h 50m
1h 25m
2h 35m
9h 50m
14h 45m
12h 10m
23h 45m
21h 35m
17h 55m
2h 40m
2h 25m
2h 50m
5h 30m
14h 10m
14h 5m
14h 5m
2h 45m
5h 25m
3h 40m
9h 30m
8h 40m
9h 10m
15h 20m
3h 15m
9h 50m
23h 20m
21h 5m
10h 30m
6h 35m
1h 30m
5h 15m
10h 25m
5h 5m
9h
2h 55m
7h 15m
15h 30m
11h
23h 30m
15h
3h
29h 35m
4h 25m
11h
2h 35m
8h 20m
2h 45m
11h
1h 30m
10h 30m
2h 45m
13h 30m
2h 50m
25h 20m
22h 5m
9h 5m
25h 30m
13h 30m
2h 50m
5h 5m
6h 15m
2h 45m
2h 35m
5h 20m
17h 30m
14h 30m
6h 15m
22h 5m
1h 30m
3h
3h 10m
5h 45m
9h 15m
2h 20m
14h 55m
2h 50m
10h 5m
14h 50m
7h 15m
25h 55m
27h 35m
3h 15m
25h 30m
2h 35m
2h 45m
1h 20m
11h 45m
9h
12h 50m
2h 55m
6h 15m
23h 10m
14h 20m
10h 15m
27h 50m
3h 5m
2h 30m
26h 35m
11h 50m
7h 20m
1h 25m
2h 50m
2h 15m
2h 55m
3h
16h 50m
24h 50m
16h 5m
2h 20m
13h 20m
7h 30m
18h 20m
2h 50m
25h 35m
1h 35m
21h 25m
38h 35m
2h 55m
27h 40m
27h 35m
11h 15m
1h 25m
12h
1h 30m
1h 30m
15h 50m
37h 25m
8h 25m
26h 20m
10h 25m
10h 25m
2h 15m
8h 55m
14h 45m
7h 15m
12h 35m
3h
2h 35m
2h 55m
9h 30m
7h 35m
2h 25m
7h 20m
6h 25m
26h 10m
9h 15m
8h 25m
11h
3h
19h 25m
5h 25m
2h 50m
2h 45m
8h 20m
2h 15m
8h
2h 40m
1h 30m
12h 35m
1h 15m
10h 25m
3h
23h 55m
16h 5m
5h 20m
24h 35m
4h 55m
6h 10m
1h 30m
2h 20m
5h 15m
7h 5m
12h 30m
2h 45m
6h 15m
20h
3h 15m
8h
7h 40m
13h 30m
22h 45m
2h 35m
22h 45m
10h 15m
13h 30m
2h 30m
5h 15m
6h 35m
16h 5m
3h
9h 50m
23h
2h 50m
5h 20m
11h
14h 50m
23h 30m
36h 10m
20h 55m
3h 15m
3h 15m
9h 20m
5h 15m
1h 30m
7h 30m
2h 35m
14h 20m
21h 20m
10h 30m
24h 45m
3h 15m
22h 15m
27h 20m
6h
2h 50m
7h 50m
5h
3h 15m
2h 50m
2h 40m
21h 55m
8h 40m
1h 30m
15h 30m
8h 40m
6h 20m
5h 35m
12h 30m
2h 50m
11h 35m
3h 5m
26h 30m
9h
2h 45m
13h 20m
20h 15m
8h 15m
1h 25m
10h 30m
20h
22h 25m
9h
1h 30m
5h 20m
17h 5m
13h 30m
13h 25m
2h 15m
11h 50m
2h 30m
8h
11h 20m
13h 30m
13h 55m
20h 55m
10h 40m
27h 5m
3h
18h 50m
22h 55m
11h 15m
2h 40m
20h 10m
15h 10m
25h 55m
5h
29h 50m
7h 35m
2h 50m
28h 20m
21h 40m
22h 45m
24h 10m
7h 5m
12h 40m
2h 25m
2h 45m
24h 35m
19h
2h 40m
3h
23h 55m
11h 5m
1h 30m
2h 50m
2h 40m
5h 10m
27h 5m
14h
2h 55m
4h 50m
10h
5h 55m
12h 45m
15h 15m
12h 25m
10h
3h
2h 30m
10h 20m
27h 5m
1h 30m
16h 15m
13h 50m
2h 35m
23h
3h 5m
3h
3h
2h 30m
1h 30m
20h
2h 40m
2h 20m
2h 40m
8h 30m
2h 45m
7h 15m
2h 25m
2h 20m
7h 30m
4h 25m
2h 50m
14h
2h 55m
13h 50m
2h 55m
20h 25m
23h 40m
9h
7h 15m
2h 55m
17h 55m
8h 15m
9h 15m
16h 5m
2h 45m
2h 50m
11h 35m
5h 20m
1h 25m
15h
2h 35m
20h 10m
2h 50m
2h 35m
2h 50m
5h 20m
38h 15m
4h 25m
15h 15m
12h 45m
25h 5m
12h 30m
9h 35m
1h 30m
9h 20m
11h 50m
6h 25m
5h 15m
7h 30m
1h 30m
11h 55m
7h 20m
22h 45m
2h 45m
11h 30m
26h 20m
42h 5m
13h 20m
4h 25m
2h 30m
13h 50m
4h 50m
7h
3h 15m
20h 20m
2h 45m
2h 20m
2h 50m
2h 30m
3h 5m
24h 35m
30h 40m
13h 20m
2h 35m
2h 35m
7h 50m
26h 35m
29h 35m
5h 30m
16h 5m
11h 50m
12h 30m
15h 5m
30h 20m
2h 50m
26h 20m
27h 5m
28h
21h 15m
27h 40m
26h 10m
4h 50m
2h 25m
1h 25m
4h 35m
1h 30m
4h 50m
27h 35m
5h
17h 20m
10h
8h
3h 5m
2h 35m
7h 20m
23h 30m
26h 55m
9h 30m
23h 35m
28h 50m
13h 20m
16h 5m
13h 55m
2h 50m
6h 30m
12h 55m
2h 25m
2h 55m
2h 55m
7h 5m
2h 30m
2h 40m
7h 15m
12h
2h 50m
2h 25m
2h 30m
21h 5m
13h 30m
15h 20m
2h 55m
3h
15h 10m
7h 35m
2h 20m
2h 20m
13h 50m
1h 30m
15h 55m
6h
2h 35m
22h 25m
7h 40m
23h 5m
2h 20m
2h 30m
2h 45m
21h 35m
2h 15m
2h 40m
6h 15m
23h 5m
9h 50m
3h
11h 5m
21h 40m
10h 30m
3h 5m
5h 5m
2h 25m
6h
4h 5m
38h 35m
2h 15m
11h 30m
16h 35m
14h 25m
2h 55m
3h
6h 20m
16h 5m
5h 45m
2h 50m
9h
12h 45m
2h 55m
15h 20m
7h 15m
10h 25m
12h 30m
2h 30m
2h 30m
19h 30m
2h 50m
22h
2h 50m
29h 55m
13h 5m
37h 20m
13h 15m
3h
9h 30m
30h 45m
12h 10m
14h 5m
4h 40m
8h 5m
15h 10m
5h 45m
1h 30m
13h 10m
2h 30m
8h 55m
2h 55m
2h 55m
7h 5m
1h 20m
18h
28h 40m
7h 35m
10h 40m
24h 50m
2h 50m
22h 10m
11h 40m
5h 15m
11h 25m
13h 30m
9h
6h 35m
2h 55m
2h 30m
12h 30m
2h 40m
2h 35m
5h 45m
22h 10m
25h 20m
2h 15m
33h 15m
22h 45m
8h
7h 40m
2h 35m
13h 20m
3h 5m
25h
21h 35m
26h 55m
6h
9h
2h 50m
15h
12h 25m
2h 50m
1h 30m
14h 10m
2h 45m
8h 35m
21h 15m
1h 20m
25h 30m
25h 50m
25h 40m
6h 35m
3h
2h 50m
11h 5m
2h 50m
2h 25m
17h 40m
3h
3h
9h 35m
5h 30m
17h 55m
16h 15m
2h 50m
9h 40m
15h 55m
1h 25m
5h 20m
13h 5m
22h 55m
2h 25m
8h 30m
23h 40m
2h 45m
2h 55m
7h 30m
13h 55m
19h 25m
15h 10m
10h 10m
11h 30m
2h 50m
6h 15m
21h 55m
11h 45m
8h
11h 30m
18h 20m
2h 25m
8h 55m
2h 30m
17h 40m
11h 35m
5h 15m
1h 30m
3h
9h
2h 45m
25h 45m
3h
10h 35m
15h
2h 45m
2h 15m
16h 55m
25h 45m
14h 55m
9h 5m
14h 5m
8h
4h 10m
10h 30m
16h 45m
8h 30m
3h 40m
23h 50m
2h 30m
21h 50m
10h 15m
2h 25m
6h 40m
10h 15m
25h 15m
2h 50m
11h 10m
2h 50m
13h 20m
12h 45m
10h 30m
2h 40m
7h 35m
12h
26h 10m
14h 45m
23h 15m
5h 30m
2h 35m
1h 35m
10h 10m

10h 50m
3h 5m
2h 20m
11h 45m
10h 10m
11h 40m
28h 15m
9h
24h 45m
19h 10m
1h 30m
26h 35m
12h 15m
7h 50m
12h 45m
2h 40m
2h 50m
2h 30m
1h 20m
24h 45m
7h 30m
9h
2h 50m
8h
14h 40m
17h 25m
14h 45m
2h 45m
26h 55m
12h 10m
2h 50m
12h 30m
6h 30m
14h 25m
16h 55m
3h 15m
2h 30m
14h 25m
1h 30m
25h 45m
19h 30m
22h 55m
11h 5m
20h 55m
6h 35m
21h 20m
3h 55m
2h 50m
12h 45m
2h 50m
6h 35m
2h 20m
2h 55m
2h 20m
12h
14h 25m
2h 15m
13h 30m
25h 45m
2h 50m
24h 50m
12h 35m
11h 50m
26h 55m
8h 50m
19h 25m
12h 15m
7h 35m
19h 30m
5h 20m
8h 20m
2h 45m
28h 50m
13h 20m
23h 45m
19h
22h 30m
2h 35m
2h 15m
5h 30m
2h 35m
39h 5m
9h
12h 30m
4h 25m
8h 55m
12h
9h 15m
2h 35m
16h
27h 40m
6h 30m
12h 10m
5h 15m
2h 50m
12h 45m
8h 5m
26h 55m
19h 25m
6h 30m
1h 25m
11h 45m
10h 40m
16h 25m
2h 50m
13h 30m
5h 40m
3h 50m
1h 30m
10h 30m
2h 45m
2h 35m
1h 30m
12h 35m
5h 45m
3h 5m
2h 55m
5h 50m
4h 45m
2h 55m
12h 15m
8h 25m
27h 35m
2h 30m
8h 40m
2h 55m
3h
17h 20m
2h 35m
4h 55m
2h 50m
16h 15m
5h 45m
7h 50m
2h 50m
27h 35m
14h 25m
27h 45m
6h 25m
15h 10m
3h 35m
12h 15m
5h 5m
4h 55m
3h 5m
3h 40m
22h 15m
10h 30m
2h 35m
12h 55m
2h 35m
2h 50m
7h 45m
28h 5m
12h 25m
2h 45m
25h 5m
2h 35m
13h
20h 35m
21h 35m
9h 50m
12h 45m
24h 45m
1h 30m
13h 45m
4h 20m
22h 30m
2h 55m
1h 20m
14h 25m
7h 15m
3h
3h 10m
3h 5m
17h 25m
14h 45m
6h 10m
2h 30m
2h 55m
2h 55m
18h 25m
22h 30m
8h
28h 5m
13h 45m
2h 55m
2h 55m
2h 20m
8h 25m
28h 40m
24h 55m
1h 30m
11h 15m
5h 5m
1h 30m
24h 35m
26h 50m
9h 20m
1h 30m
24h 45m
10h 30m
13h 30m
5h 45m
26h 25m
6h 5m
11h 30m
16h
13h 20m
22h 55m
3h 10m
13h 20m
9h 50m
1h 30m
3h 50m
7h 50m
5h 55m
1h 15m
4h 55m
9h 30m
7h 30m
2h 15m
2h 30m
17h 20m
14h
2h 20m
20h 25m
1h 30m
2h 45m
23h 50m
12h 5m
2h 45m
11h 30m
9h 30m
5m
2h 50m
38h 35m
5h 30m
26h 30m
2h 55m
1h 30m
4h 25m
1h 25m
1h 25m
4h
2h 55m
5h 5m
2h 40m
8h 25m
2h 50m
13h
9h 30m
20h 25m
2h 40m
30h
14h 50m
2h 40m
2h 50m
2h 35m
24h
13h 20m
9h 35m
1h 25m
9h 45m
16h 45m
2h 45m
11h
8h 15m
2h 20m
4h 25m
24h 35m
3h
21h 40m
1h 35m
2h 40m
16h 15m
12h 55m
2h 40m
11h 45m
2h 20m
2h 45m
2h 50m
3h 15m
3h 15m
2h 45m
17h 5m
2h 40m
3h 15m
2h 50m
11h 55m
14h 10m
2h 35m
23h 35m
11h 45m
2h 55m
1h 30m
7h 5m
2h 20m
14h
1h 25m
10h 40m
9h 30m
25h 45m
12h
2h 50m
2h 50m
21h 20m
13h 20m
6h 35m
3h 15m
1h 30m
5h 35m
8h
2h 45m
2h 55m
9h 50m
5h 45m
25h 45m
2h 50m
22h 25m
11h 55m
7h 30m
3h 5m
2h 35m
7h 30m
7h 30m
14h 5m
14h 45m
22h 15m
6h 15m
6h 30m
2h 55m
2h 30m
1h 15m
4h 5m
8h 25m
14h 50m
17h 35m
3h
2h 50m
18h 45m
2h 35m
1h 25m
27h 10m
2h 35m
5h 45m
6h 25m
9h 30m
8h 50m
5h 55m
5h 5m
6h 35m
2h 35m
2h 55m
2h 50m
11h 15m
7h 55m
9h
23h 20m
13h 55m
10h 25m
6h 35m
7h 20m
10h 25m
12h 25m
14h 20m
12h 5m
3h
3h
17h 25m
27h 10m
8h 55m
15h
2h 45m
2h 50m
11h
15h 40m
4h
23h 45m
14h 5m
14h 25m
2h 55m
2h 35m
11h 45m
13h 30m
2h 30m
12h 30m
5h 55m
15h 55m
2h 50m
2h 35m
3h
8h 40m
3h
15h 40m
7h 20m
2h 50m
2h 45m
8h 25m
4h 25m
7h 40m
20h 35m
7h
25h 30m
2h 40m
13h 45m
13h
3h
26h 10m
13h 30m
10h 15m
14h 55m
4h 50m
14h 55m
2h 55m
13h 50m
2h 15m
2h 45m
21h 15m
16h 30m
3h
14h 30m
16h
10h 55m
5h
1h 25m
6h 30m
16h 5m
23h 10m
27h 40m
26h 55m
25h 55m
16h 5m
2h 45m
2h 55m
13h 10m
2h 55m
13h
10h 40m
9h 15m
10h 30m
23h 35m
16h 50m
13h 40m
22h
17h 45m
10h 20m
1h 30m
17h 5m
21h 35m
12h 10m
13h
1h 20m
8h 55m
14h 10m
2h 25m
3h
7h 55m
2h 20m
16h 5m
2h 25m
9h 15m
13h 10m
2h 55m
2h 35m
3h
2h 45m
4h
5h
1h 30m
19h 5m
2h 30m
7h 20m
4h 30m
1h 30m
10h 35m
2h 15m
1h 30m
14h 35m
3h
2h 20m
10h 55m
7h 55m
27h 35m
1h 30m
12h 40m
13h 50m
1h 30m
3h 15m
6h 35m
19h 55m
2h 50m
5h 45m
2h 30m
10h 20m
8h 55m
2h 50m
2h 20m
3h
6h 35m
15h
4h 50m
13h 50m
26h 5m
2h 50m
14h 45m
6h 55m
26h 30m
24h 30m
10h 25m
9h 35m
2h 20m
2h 50m
2h 30m
15h 30m
16h 10m
2h 20m
17h 5m
18h 45m
5h
14h 20m
8h 25m
5h 10m
12h 15m
9h 15m
9h 50m
2h 35m
20h 15m
16h 50m
17h 45m
2h 45m
1h 30m
16h 20m
2h 50m
9h 50m
15h
15h 10m
8h 20m
25h 35m
2h 15m
14h
2h 50m
24h 55m
14h 30m
13h
1h 15m
7h 35m
27h 40m
2h 50m
7h 20m
1h 30m
2h 55m
2h 30m
26h 20m
2h 40m
3h
2h 35m
25h 55m
6h 30m
12h 25m
5h 15m
21h 10m
2h 45m
3h
29h 5m
2h 55m
15h 30m
7h 5m
18h 45m
2h 15m
2h 40m
7h 50m
27h 40m
24h 40m
7h 15m
12h 25m
6h 15m
8h
6h 10m
21h 40m
15h 20m
9h 45m
23h 50m
13h 25m
14h 5m
13h
2h 35m
3h 15m
9h 30m
32h 5m
2h 30m
2h 30m
23h
15h 30m
11h 35m
23h
2h 35m
1h 30m
8h 35m
2h 55m
2h 45m
17h 15m
2h 50m
3h
20h 20m
15h 40m
2h 50m
1h 30m
2h 15m
32h 30m
14h 10m
9h 35m
20h 10m
7h 30m
4h 5m
11h 15m
2h 45m
2h 35m
9h 20m
2h 35m
8h 10m
2h 55m
8h 20m
2h 35m
3h
4h 55m
5h
8h 55m
6h 25m
5h
24h 5m
3h
2h 30m
20h 10m
15h 30m
1h 30m
1h 20m
1h 20m
2h 35m
1h 30m
3h 5m
2h 55m
4h 25m
2h 50m
38h
12h 55m
9h 20m
11h 25m
2h 55m
6h 5m
2h 35m
2h 50m
20h 45m
7h 5m
15h
14h 5m
23h 15m
14h 50m
26h 35m
9h
2h 45m
18h 10m
2h 15m
13h 20m
9h 20m
26h 45m
3h 5m
2h 35m
2h 30m
9h 40m
5h 15m
2h 40m
12h 45m
2h 45m
19h 55m
11h 15m
25h 20m
2h 50m
2h 55m
2h 20m
15h 10m
26h 20m
9h 5m
2h 50m
10h 25m
6h 25m
15h 5m
13h 30m
27h 35m
4h 25m
14h 30m
23h 40m
24h
13h 20m
2h 45m
1h 30m
2h 50m
25h 30m
11h 50m
28h
17h 15m
10h
2h 20m
2h 50m
12h 45m
12h 25m
2h 35m
8h 20m
2h 25m
15h 10m
5h 30m
13h 30m
5h 20m
10h 40m
17h 5m
9h 15m
11h 25m
2h 30m
12h 30m
28h 50m
2h 55m
9h 15m
24h 55m
3h 40m
9h 30m
11h
2h 45m
25h 5m
23h 35m
1h 30m
19h 5m
3h 15m
29h 35m
22h 45m
28h 20m
2h 35m
2h 20m
2h 30m
2h 35m
2h 50m
24h
2h 50m
8h 40m
2h 50m
16h
18h 50m
22h
32h 5m
20h 55m
4h 50m
2h 50m
12h 40m
23h 50m
14h 55m
1h 20m
17h 5m
1h 25m
26h 50m
2h 35m
3h
21h 15m
35h 15m
7h 30m
2h 55m
2h 50m
7h 5m
12h 15m
2h 50m
2h 20m
1h 30m
22h 30m
8h 20m
2h 20m
6h 25m
18h 25m
15h 25m
21h 20m
9h 15m
2h 20m
6h 15m
2h 35m
10h 40m
13h 55m
1h 25m
2h 45m
2h 25m
2h 45m
3h
2h 30m
26h 30m
14h 20m
13h 25m
8h 45m
5h 20m
5h 5m
2h 45m
3h 15m
26h 50m
12h 45m
1h 30m
2h 35m
2h 55m
2h 30m
9h 20m
26h 10m
1h 20m
7h 15m
2h 35m
5h 10m
6h 15m
8h 5m
9h 20m
7h 30m
7h 45m
2h 50m
5h 45m
12h 10m
6h 40m
2h 50m
27h 10m
7h 15m
5h 40m
13h 45m
21h 5m
7h 5m
3h 15m
2h 50m
19h 10m
14h
24h 30m
2h 35m
15h 15m
2h 20m
2h 50m
11h 55m
19h 30m
8h 55m
12h 10m
2h 45m
24h 25m
2h 50m
19h 45m
9h 15m
1h 30m
2h 50m
2h 40m
20h 10m
9h 50m
18h 45m
2h 20m
2h 45m
5h 35m
2h 35m
7h 35m
7h 20m
5h 30m
1h 25m
2h 45m
2h 25m
5h 20m
31h 55m
7h 40m
28h 20m
7h 25m
21h 15m
16h 5m
2h 40m
9h 50m
2h 45m
21h 40m
2h 55m
11h
21h 25m
2h 50m
28h 40m
14h 20m
20h 15m
12h 10m
10h 25m
13h 30m
5h 10m
9h
2h 55m
11h
30h 20m
2h 50m
4h 40m
27h 35m
3h 10m
2h 50m
28h 20m
23h 50m
12h 45m
22h
5h 20m
2h 55m
8h 55m
2h 55m
4h 45m
8h 5m
2h 50m
9h
2h 50m
23h 40m
2h 20m
2h 30m
17h 30m
11h 30m
2h 40m
16h 20m
15h 20m
1h 25m
15h 25m
2h 50m
3h
16h 45m
18h 10m
11h 15m
12h
11h 30m
3h
3h 40m
2h 35m
21h 15m
10h 50m
3h
16h 15m
17h 35m
9h 35m
9h
10h 20m
2h 35m
17h 15m
2h 55m
2h 15m
19h 25m
16h 15m
5h 5m
2h 35m
16h 55m
8h 40m
21h 35m
5h 55m
13h 30m
9h 30m
19h 55m
2h 45m
23h 50m
20h 35m
37h 25m
2h 30m
2h 50m
15h 45m
14h 5m
2h 30m
8h 25m
7h 5m
11h 30m
23h 15m
5h 45m
1h 30m
5h 30m
2h 35m
5h 55m
11h 5m
11h 40m
3h 15m
3h 5m
24h
17h 35m
22h 55m
2h 40m
15h
1h 20m
4h 40m
8h 55m
16h 5m
24h 30m
2h 20m
8h 40m
4h 55m
12h 55m
1h 30m
12h 30m
2h 35m
17h 55m
24h 35m
7h 30m
2h 55m
21h 15m
2h 30m
3h
37h 20m
23h 30m
13h 15m
2h 55m
9h 50m
2h 50m
1h 30m
1h 15m
21h 35m
2h 50m
6h 40m
13h 25m
10h 15m
15h 10m
18h 20m
2h 15m
26h 35m
26h 25m
6h 15m
2h 55m
13h 20m
2h 50m
7h 30m
1h 30m
15h 25m
1h 25m
7h 30m
22h 55m
20h 10m
3h 15m
11h 45m
2h 30m
9h 10m
2h 45m
15h 45m
18h 25m
11h 25m
27h 45m
15h 25m
1h 30m
5h 15m
7h 15m
9h 15m
16h 5m
25h 40m
23h 30m
2h 50m
9h
3h
16h 15m
2h 50m
29h 20m
2h 25m
2h 30m
16h 5m
23h 10m
2h 45m
6h 20m
15h 30m
12h 10m
1h 30m
10h 25m
12h 40m
8h 35m
7h 20m
23h 40m
1h 25m
15h 30m
16h 50m
2h 50m
18h
7h 20m
17h 55m
2h 50m
38h 15m
16h 45m
9h 50m
6h 35m
13h 45m
27h 45m
6h 20m
5h 45m
2h 55m
5h 20m
1h 30m
12h
15h 10m
5h 5m
2h 50m
7h 20m
14h 25m
2h 35m
3h
2h 55m
25h 50m
16h 50m
2h 35m
38h 20m
14h
16h 10m
11h 15m
13h 15m
1h 30m
2h 50m
7h 30m
9h 25m
3h
5h 15m
24h 25m
3h
5h 30m
8h 55m
18h 30m
22h 55m
2h 15m
2h 30m
10h 25m
18h 25m
2h 50m
8h 20m
27h
3h 40m
14h 25m
2h 50m
13h
2h 20m
16h 40m
2h 40m
2h 35m
1h 30m
1h 30m
2h 50m
2h 35m
26h 40m
7h 30m
2h 15m
18h 45m
20h 15m
2h 40m
2h 45m
5h 25m
12h
12h
5h 15m
2h 55m
9h 30m
2h 30m
19h 15m
2h 55m
5h 50m
8h 15m
3h
26h 55m
2h 25m
12h 55m
14h 5m
14h 25m
2h 50m
2h 55m
10h 10m
1h 15m
23h 25m
3h 5m
2h 50m
8h 40m
11h 30m
4h 50m
29h 55m
7h 5m
18h 45m
30h 20m
8h 10m
2h 35m
2h 30m
5h 10m
11h
10h 15m
28h 10m
3h 40m
2h 50m
1h 20m
2h 50m
2h 30m
12h 15m
8h 35m
1h 35m
27h
12h 45m
13h 30m
1h 30m
26h 55m
5h 25m
1h 25m
28h 50m
11h 45m
4h 35m
20h
14h 55m
2h 35m
2h 15m
2h 50m
28h 20m
16h
23h 15m
2h 40m
5h 35m
2h 20m
30h 20m
6h
16h 50m
7h
5h 45m
2h 50m
33h 20m
13h 30m
21h 35m
16h 50m
12h 10m
2h 40m
16h 10m
6h 25m
19h 55m
6h 30m
14h 30m
11h 50m
10h 30m
7h 35m
23h 30m
2h 50m
27h 45m
9h 30m
7h 20m
2h 35m
3h
7h 30m
2h 35m
27h
12h
8h
26h 35m
9h 15m
8h 30m
16h 50m
28h 10m
2h 55m
2h 50m
12h 30m
15h 10m
1h 30m
8h 35m
23h 50m
16h 50m
9h 30m
27h
2h 20m
9h 30m
2h 50m
2h 50m
2h 55m
4h
22h 5m
3h
19h 30m
21h 35m
2h 45m
21h 5m
27h 10m
2h 30m
5h 45m
2h 45m
2h 50m
19h 30m
2h 55m
3h 10m
2h 45m
11h 35m
1h 25m
2h 55m
2h 55m
11h
13h 55m
2h 45m
6h 35m
16h 10m
2h 20m
22h 55m
2h 15m
1h 30m
2h 50m
27h
3h 40m
23h 45m
12h 45m
7h 20m
24h 55m
25h 10m
10h
5h 55m
25h 20m
10h 20m
6h 40m
3h
25h 30m
23h
2h 25m
12h 40m
20h 45m
26h 15m
2h 25m
7h 55m
3h
2h 55m
11h 45m
2h 55m
7h 50m
1h 30m
14h
2h 50m
13h 15m
26h 20m
12h
37h 25m
10h 40m
9h 35m
5h 30m
25h 30m
1h 30m
2h 20m
2h 35m
7h 5m
9h 15m
2h 30m
1h 30m
1h 20m
5h 45m
8h 25m
6h
3h
2h 20m
2h 55m
8h 25m
2h 35m
7h 5m
9h 5m
6h 20m
2h 55m
20h 10m
2h 25m
10h 15m
26h 50m
14h 20m
10h 20m
13h
5h
27h 30m
8h 55m
24h
26h 55m
16h 5m
18h 55m
28h 15m
24h 50m
3h 10m
7h 20m
2h 55m
2h 25m
2h 30m
23h 55m
11h 5m
6h 15m
16h 5m
1h 25m
20h 25m
7h 35m
5h 10m
23h 10m
1h 30m
12h 45m
8h 40m
36h 10m
38h 35m
21h 25m
12h 15m
12h 40m
8h
10h 30m
26h 20m
13h 25m
24h
9h 5m
8h 55m
2h 50m
13h 20m
24h
34h 5m
15h 25m
23h 15m
25h 45m
10h 25m
10h
4h 35m
2h 55m
27h 35m
2h 50m
1h 30m
3h 15m
8h 55m
6h 55m
12h 10m
6h 5m
16h 25m
5h 15m
13h 30m
13h 20m
2h 55m
23h
20h
25h 55m
23h
7h 15m
23h 20m
26h 55m
8h 10m
12h 45m
5h
2h 15m
10h 15m
8h 45m
7h 15m
5h 55m
4h 30m
2h 20m
11h 20m
9h 15m
13h 30m
3h
2h 50m
2h 20m
2h 50m
2h 50m
27h 20m
5h 5m
14h
12h 20m
26h 40m
9h 35m
2h 35m
1h 25m
2h 35m
23h 40m
28h 5m
2h 50m
16h 5m
3h 15m
20h 10m
12h 35m
3h
11h 5m
16h 5m
22h 30m
24h 30m
15h 30m
12h 15m
14h 20m
22h
22h 40m
14h 10m
15h 45m
2h 20m
3h
14h 35m
24h 50m
2h 50m
5h 15m
4h 50m
13h 30m
12h
2h 30m
7h 15m
10h 25m
5h 15m
11h 25m
9h
25h 45m
26h 15m
8h 40m
2h 50m
3h
2h 30m
2h 35m
2h 35m
2h 15m
12h 25m
13h 30m
2h 40m
7h 20m
3h
5h 40m
2h 25m
3h
4h
2h 35m
9h 15m
2h 55m
3h
4h 30m
17h 35m
13h 15m

24h 55m
7h 15m
2h 30m
22h
2h 50m
11h 30m
2h 55m
12h 25m
2h 20m
14h
30h 30m
21h 20m
9h 25m
19h 30m
29h 20m
7h 15m
8h 15m
2h 55m
13h 25m
1h 15m
24h 15m
10h 20m
20h 55m
5h 15m
1h 30m
2h 50m
9h
13h 30m
2h 45m
14h 25m
2h 50m
21h 5m
18h 45m
2h 50m
6h 55m
6h 35m
2h 50m
5h 30m
13h 20m
9h
10h 15m
13h 20m
2h 45m
2h 45m
13h 45m
9h 20m
2h 20m
2h 40m
8h 55m
2h 50m
2h 15m
2h 55m
24h 30m
23h 10m
22h 55m
9h 20m
23h 10m
3h 5m
18h
10h 15m
2h 35m
25h 25m
16h 15m
2h 45m
2h 55m
27h 35m
9h 55m
2h 40m
1h 30m
18h 30m
21h 25m
1h 20m
3h 5m
2h 30m
3h
2h 30m
25h 35m
13h 25m
2h 15m
2h 15m
7h 55m
2h 50m
10h
1h 30m
17h 45m
2h 45m
3h
5h 5m
15h
11h 30m
4h 50m
11h 50m
2h 20m
2h 40m
1h 25m
2h 55m
1h 30m
3h 10m
2h 20m
2h 40m
2h 45m
1h 30m
25h 55m
2h 45m
17h 5m
17h 20m
23h
19h 5m
2h 55m
8h 25m
2h 35m
26h 20m
2h 25m
9h 30m
2h 35m
24h 40m
18h 25m
8h
2h 20m
2h 45m
1h 30m
2h 20m
16h
16h 10m
2h 55m
4h 30m
16h 15m
5h 30m
2h 20m
21h 15m
5h
24h 30m
2h 55m
11h 45m
5h 55m
26h 25m
38h
13h 55m
6h 15m
17h 25m
2h 20m
14h 30m
2h 20m
1h 25m
8h 10m
7h 55m
23h 10m
6h 45m
2h 50m
2h 30m
27h 20m
2h 45m
3h
27h 25m
10h 15m
6h 5m
23h 40m
9h 40m
23h 40m
5h 30m
2h 45m
9h 30m
7h 50m
22h 30m
25h 35m
6h 5m
41h 20m
26h
9h
22h 10m
7h 50m
2h 45m
13h 30m
6h 5m
8h 40m
11h 20m
2h 45m
8h 25m
5h 30m
13h 30m
8h 40m
7h 30m
6h 15m
30h 30m
15h 55m
26h 55m
2h 30m
14h 35m
26h 50m
2h 45m
2h 50m
1h 25m
2h 20m
16h 50m
2h 50m
3h
4h 40m
2h 45m
10h 50m
4h 55m
1h 25m
16h 50m
27h
6h
7h 30m
11h 25m
24h 50m
24h 45m
8h 5m
9h 30m
15h 55m
13h 20m
1h 30m
18h 20m
2h 20m
2h 45m
2h 15m
5h 30m
12h 20m
5h 35m
26h
2h 20m
19h 30m
2h 50m
11h
13h 50m
3h 15m
3h
10h 30m
2h 50m
26h 50m
26h 40m
23h 45m
4h 40m
1h 25m
5h 20m
32h 30m
5h
27h 5m
7h 55m
25h 45m
5h
27h 35m
4h 55m
18h 20m
14h 30m
23h 15m
2h 35m
9h 30m
23h 30m
2h 20m
10h 20m
1h 30m
8h 25m
15h 25m
6h 20m
2h 55m
3h 5m
5h 30m
5h 30m
22h 45m
12h 5m
2h 30m
16h 5m
23h 45m
4h 35m
26h
7h 15m
24h
16h 5m
14h 5m
23h 15m
10h
3h 50m
20h 10m
2h 40m
9h 25m
2h 15m
2h 45m
27h 20m
15h 10m
2h 35m
12h 40m
25h 15m
18h 20m
20h 5m
2h 40m
5h 45m
12h 20m
26h 25m
5h 45m
3h
18h 50m
27h 10m
1h 20m
15h 40m
6h 30m
12h 55m
5h 45m
6h 55m
10h 30m
20h 25m
20h 10m
9h 35m
2h 35m
1h 25m
5h 30m
16h 50m
2h 45m
26h 40m
11h
13h 30m
28h 5m
11h
2h 50m
9h
15h 15m
2h 50m
2h 50m
5h
3h
1h 30m
2h 45m
5h 30m
5h 10m
33h 15m
7h 35m
12h 30m
21h 50m
18h 45m
2h 45m
24h 45m
2h 50m
2h 35m
5h 5m
2h 45m
29h 5m
14h 25m
13h 15m
2h 55m
7h 45m
16h 5m
13h 55m
11h 30m
23h 55m
1h 30m
21h 35m
19h 40m
1h 30m
10h 20m
2h 20m
1h 25m
2h 50m
4h 40m
2h 20m
24h 55m
2h 40m
10h 20m
9h 30m
26h
18h 45m
1h 30m
2h 15m
14h
8h 45m
23h 50m
2h 50m
19h 5m
18h 45m
15h 20m
1h 30m
10h 20m
26h
2h 20m
8h
10h 30m
1h 25m
2h 20m
2h 50m
9h 30m
5h 15m
14h 45m
2h 45m
10h 20m
2h 50m
9h 25m
26h 35m
38h 15m
13h 25m
7h 35m
11h 15m
1h 25m
2h 50m
8h 20m
3h 5m
23h 40m
2h 20m
22h 55m
23h 40m
5h 40m
2h 30m
20h 55m
3h 5m
13h 20m
2h 20m
1h 25m
2h 35m
3h 40m
26h 55m
7h 30m
11h
27h 20m
2h 50m
38h
19h 25m
13h 30m
3h
27h
4h 55m
6h
10h 25m
12h 30m
3h
8h 5m
2h 20m
13h 20m
5h 25m
19h 5m
2h 45m
14h 30m
24h 5m
1h 30m
26h 55m
2h 20m
23h 40m
8h 30m
23h 30m
8h
30h 20m
2h 50m
23h 30m
22h 55m
29h 55m
5h 15m
15h 20m
6h 25m
10h 40m
2h 45m
23h 40m
16h
10h
4h 50m
5h 5m
20h 10m
14h 55m
30h 30m
2h 30m
2h 55m
1h 25m
2h 50m
11h 5m
5h 5m
30h 30m
2h 50m
13h 25m
3h
10h 15m
20h 55m
10h 45m
8h
12h 10m
21h 25m
8h 25m
9h 10m
8h 10m
4h 55m
21h 15m
3h
14h 20m
2h 35m
6h 35m
9h 30m
10h 20m
1h 30m
8h 10m
2h 45m
14h 5m
16h 15m
21h 20m
5h 20m
6h 20m
6h 25m
2h 30m
13h 55m
2h 35m
8h 55m
22h 30m
13h 30m
13h 30m
2h 20m
3h 5m
5h
5h
10h 25m
11h 55m
14h 5m
18h 45m
30h 20m
26h 40m
6h 20m
8h 40m
24h 20m
2h 55m
6h 40m
16h 20m
2h 45m
19h 55m
6h 5m
3h
2h 55m
33h 15m
2h 35m
2h 35m
3h
2h 30m
15h 20m
2h 30m
18h 15m
9h 20m
2h 30m
2h 20m
7h 15m
6h 25m
27h 20m
8h 55m
26h 20m
13h 30m
7h 30m
11h 50m
4h 25m
6h 35m
22h 15m
1h 30m
1h 35m
2h 20m
14h 25m
2h 30m
22h 55m
2h 20m
9h 50m
26h 10m
18h
16h 5m
2h 45m
14h 55m
5h 25m
8h 40m
2h 45m
22h 25m
13h 20m
3h 15m
2h 30m
1h 25m
6h 20m
7h 35m
23h 35m
2h 20m
19h 15m
2h 55m
9h 35m
22h 55m
3h
2h 30m
1h 30m
1h 30m
30h 30m
12h 30m
25h 5m
6h
21h 15m
10h 30m
2h 20m
15h 10m
2h 50m
7h 5m
5h 30m
2h 40m
7h 40m
2h 45m
2h 35m
2h 35m
2h 20m
2h 35m
1h 30m
2h 25m
13h 25m
1h 30m
6h 5m
10h 50m
18h 20m
14h 35m
2h 50m
11h 5m
2h 30m
23h 50m
26h 55m
3h
7h 35m
31h 50m
3h 15m
7h 15m
15h 10m
18h 45m
18h 20m
25h 55m
1h 30m
23h 30m
5h
2h 45m
7h 50m
38h 20m
3h 10m
5h 10m
8h
3h 5m
7h 35m
9h 50m
20h 10m
21h 35m
2h 20m
2h 55m
2h 50m
4h 40m
12h 30m
10h 40m
22h 45m
16h 45m
2h 35m
24h 55m
5h 30m
2h 35m
26h 35m
5h
21h 15m
1h 30m
9h 40m
12h 25m
2h 50m
9h 45m
5h 30m
9h 50m
4h 5m
18h 45m
2h 50m
2h 35m
2h 30m
10h 5m
16h 5m
1h 30m
5h
4h 55m
2h 45m
2h 45m
14h
9h 15m
12h
1h 30m
2h 45m
21h 25m
42h 45m
2h 55m
2h 45m
38h 20m
1h 30m
1h 30m
2h 45m
23h 40m
2h 55m
2h 40m
12h 15m
8h 15m
2h 50m
1h 25m
11h
3h 15m
9h 30m
4h 55m
6h
1h 30m
10h 10m
1h 30m
6h 40m
2h 35m
16h 25m
22h 45m
7h 50m
26h 20m
2h 50m
19h 30m
3h 5m
3h 15m
2h 20m
9h 10m
2h 15m
6h
9h 50m
29h 50m
6h 25m
2h 20m
6h 15m
2h 40m
6h 15m
24h 35m
5h 45m
3h 15m
14h 55m
3h 40m
8h 5m
13h 25m
1h 25m
2h 50m
15h 35m
7h 20m
13h 55m
2h 30m
2h 50m
3h 15m
2h 40m
26h 15m
2h 50m
6h 15m
3h
4h 40m
1h 25m
12h
13h 10m
9h
6h 10m
3h 25m
1h 30m
2h 30m
3h 15m
1h 30m
10h 15m
8h 45m
2h 45m
5h
2h 45m
5h 55m
3h 35m
3h
17h 40m
2h 50m
9h 10m
9h 45m
2h 55m
26h 55m
11h 55m
11h 30m
20h 55m
5h 5m
19h 45m
17h 55m
26h
11h 45m
12h 55m
13h 20m
13h 30m
7h 35m
3h 15m
18h 25m
24h 15m
2h 50m
2h 40m
2h 20m
1h 30m
2h 50m
1h 30m
10h 20m
12h 25m
8h 40m
5h 25m
2h 55m
20h 55m
21h 25m
1h 30m
24h 40m
2h 50m
2h 15m
23h 30m
29h 20m
5h 15m
7h 5m
7h
1h 30m
7h 5m
19h 25m
29h 35m
17h 5m
12h
2h 45m
8h 40m
6h 5m
13h 20m
2h 25m
9h 50m
13h 40m
18h
6h 30m
8h 30m
10h 40m
9h 30m
4h 30m
2h 30m
10h 25m
2h 45m
12h 35m
27h 45m
21h 45m
29h 20m
2h 30m
15h 30m
23h
16h 45m
4h 40m
7h 30m
13h 30m
10h 35m
17h 5m
27h 50m
13h 25m
13h
11h
15h 5m
14h 55m
23h 35m
23h 35m
13h 20m
2h 25m
2h 30m
8h 20m
1h 30m
14h 10m
2h 20m
7h 15m
5h 25m
9h
14h 50m
1h 25m
3h
12h 55m
2h 35m
6h 15m
26h
1h 30m
14h 5m
8h
12h 10m
10h 30m
3h
5h 15m
38h
23h 30m
27h 50m
2h 45m
6h 35m
8h
16h 45m
7h 50m
10h 30m
2h 50m
4h 50m
3h
26h 35m
9h 50m
2h 50m
1h 30m
6h 35m
12h 10m
9h 50m
25h 20m
37h 10m
11h 40m
1h 30m
2h 35m
7h 5m
2h 35m
19h 55m
1h 25m
11h 5m
4h 40m
13h 30m
7h 35m
1h 25m
1h 30m
13h 50m
8h 35m
3h 15m
10h 25m
2h 20m
23h 30m
11h
18h
2h 15m
2h 15m
12h 35m
14h 20m
2h 45m
15h 40m
2h 45m
2h 30m
2h 20m
9h 15m
18h 40m
2h 50m
25h 25m
1h 20m
2h 30m
2h 50m
3h 15m
25h 45m
2h 35m
2h 35m
8h 10m
23h 40m
11h 45m
9h 20m
14h 35m
21h 35m
6h 25m
5h 35m
25h 55m
10h 15m
1h 20m
10h 20m
2h 15m
3h
23h 45m
13h 15m
3h 15m
9h 50m
18h 20m
29h 20m
7h 45m
2h 25m
7h 35m
2h 20m
3h 10m
6h 25m
16h 45m
10h 25m
13h
2h 55m
2h 35m
2h 50m
13h 30m
13h 15m
13h 30m
36h 10m
2h 25m
2h 25m
2h 50m
12h 10m
8h 25m
22h 15m
3h 5m
2h 35m
22h 55m
2h 15m
26h 20m
27h 40m
16h 45m
2h 50m
12h 30m
5h 15m
2h 50m
7h 30m
11h 55m
13h 5m
7h 20m
2h 20m
18h
8h 40m
2h 50m
20h 10m
8h
27h 20m
2h 20m
2h 20m
38h
7h 35m
5h 45m
2h 50m
2h 45m
27h 35m
3h
14h 25m
9h 20m
9h 50m
2h 20m
6h 30m
7h 35m
2h 55m
2h 50m
17h 55m
1h 20m
21h 25m
1h 30m
1h 30m
5h 20m
10h
12h 10m
16h 45m
2h 50m
10h 40m
27h 35m
25h 50m
16h 10m
30h 30m
20h 10m
2h 50m
30h 30m
26h 55m
3h 15m
6h 40m
3h
8h
27h 35m
2h 50m
25h 40m
9h 35m
2h 30m
2h 20m
10h 15m
7h 5m
1h 30m
11h 30m
2h 45m
13h 15m
14h 30m
7h 5m
12h 45m
2h 50m
2h 50m
1h 30m
25h 45m
2h 30m
27h 40m
22h 35m
2h 55m
3h 5m
2h 55m
6h 30m
14h 20m
20h
7h 45m
18h 45m
6h 40m
2h 55m
14h 20m
13h
2h 20m
16h 55m
5h 45m
19h 20m
3h 5m
27h 45m
2h 45m
2h 20m
12h 45m
17h 45m
3h
16h 35m
26h 10m
7h 35m
13h
2h 40m
3h
4h 40m
23h 50m
8h 10m
29h 20m
2h 45m
2h 50m
2h 35m
19h 5m
9h 30m
8h 40m
22h 5m
26h
2h 35m
7h 50m
10h 45m
10h 30m
14h 5m
13h 20m
2h 50m
1h 30m
19h 40m
2h 55m
23h 20m
2h 40m
16h 15m
1h 30m
9h 15m
20h 35m
2h 15m
2h 25m
3h 5m
2h 50m
5h 40m
18h 40m
25h
13h 15m
2h 30m
8h 20m
7h
25h 50m
2h 55m
9h 10m
8h 40m
2h 50m
21h 45m
6h 40m
1h 30m
7h 20m
4h
14h 5m
12h 15m
30h 30m
27h
16h 10m
9h
5h 55m
1h 25m
3h
7h 5m
2h 50m
6h 5m
2h 45m
15h 20m
23h 35m
23h 50m
13h 50m
2h 35m
4h 5m
7h 40m
2h 20m
9h 35m
9h 35m
11h 25m
12h 10m
2h 55m
1h 30m
3h 10m
12h 25m
11h 45m
11h 5m
9h 45m
17h 25m
15h
6h 20m
12h 45m
1h 30m
25h 45m
21h
9h 20m
22h 15m
8h 15m
12h 30m
8h 30m
11h 50m
10h 30m
12h 10m
5h
2h 35m
17h 25m
5h 10m
9h 30m
10h 40m
8h 40m
9h 40m
2h 15m
11h 15m
23h 30m
8h 40m
6h 20m
23h 50m
12h 55m
5h
13h 15m
2h 30m
7h
6h 35m
18h 10m
21h 25m
24h 55m
2h 50m
13h 15m
22h 10m
2h 45m
14h 25m
2h 20m
2h 30m
7h 30m
5h 45m
21h 25m
1h 30m
7h 15m
12h 30m
23h 15m
12h 5m
10h 55m
25h 20m
1h 30m
2h 55m
4h
20h 10m
13h
2h 30m
7h 5m
19h
26h 55m
12h 20m
10h 50m
9h 45m
9h 35m
18h 45m
13h
2h 40m
2h 30m
2h 30m
5h 55m
8h 30m
21h
2h 50m
3h 15m
14h 20m
8h 40m
21h 55m
8h 40m
2h 50m
11h 45m
7h 15m
5h
6h 40m
24h
5h 25m
27h
7h
10h 5m
3h
9h 10m
15h
2h 35m
5h
1h 20m
1h 30m
24h 40m
2h 45m
18h 45m
2h 50m
2h 40m
12h
11h 5m
26h 20m
21h 25m
5h 45m
14h
1h 30m
2h 50m
22h 35m
2h 55m
17h 5m
1h 30m
14h 35m
2h 35m
12h 45m
3h
12h 35m
2h 20m
17h 50m
12h 20m
14h 25m
29h 20m
2h 50m
25h 50m
22h 55m
13h
22h 35m
7h 20m
2h 20m
13h 20m
8h 40m
12h 25m
2h 50m
2h 45m
2h 35m
3h 15m
23h 40m
30h 55m
9h 30m
13h 20m
15h 20m
23h 40m
5h 45m
8h 20m
1h 25m
2h 20m
20h 55m
3h
9h 20m
1h 25m
20h 5m
22h 25m
22h 30m
9h 50m
18h 10m
2h 20m
11h 45m
11h
1h 25m
26h 10m
23h 40m
15h 20m
11h
2h 50m
5h 25m
19h 40m
15h 10m
1h 30m
27h 5m
32h 5m
13h 30m
26h 10m
23h 40m
6h 55m
3h
2h 30m
15h 25m
2h 35m
2h 50m
6h 30m
25h 40m
2h 50m
2h 35m
8h 30m
12h 15m
7h 35m
10h 30m
2h 30m
9h 30m
8h 35m
16h 15m
3h 15m
5h 15m
2h 50m
2h 50m
16h
22h 55m
6h 55m
2h 35m
2h 35m
9h 15m
26h 10m
12h
21h 40m
2h 45m
12h
27h 20m
23h 50m
12h 30m
9h 10m
12h 20m
1h 30m
5h 30m
28h
3h
1h 30m
2h 45m
5h 20m
26h 30m
26h 55m
11h 5m
2h 30m
1h 30m
7h 30m
29h 5m
17h 35m
24h 55m
29h 20m
3h
2h 40m
5h 25m
23h 50m
30h 40m
2h 45m
11h 50m
2h 35m
20h 25m
27h
2h 40m
1h 30m
1h 30m
2h 30m
2h 35m
2h 50m
2h 20m
2h 45m
2h 25m
5h 40m
27h 40m
2h 20m
5h
2h 35m
11h 30m
26h 15m
16h 45m
18h 10m
1h 30m
13h 25m
12h
2h 15m
15h 10m
6h
23h 15m
7h 15m
11h 30m
12h 35m
10h
3h
23h 50m
2h 40m
19h
1h 30m
2h 50m
2h 50m
14h 40m
2h 45m
1h 30m
30h 30m
6h
29h 30m
2h 30m
15h 10m
26h 50m
28h 5m
10h 10m
7h 30m
8h 40m
34h 30m
26h 55m
2h 55m
13h 15m
1h 35m
2h 45m
2h 40m
2h 35m
27h 5m
20h 35m
3h
3h 15m
4h 30m
3h 5m
11h
27h 5m
6h 35m
26h 10m
23h 55m
2h 30m
13h 30m
6h 30m
2h 35m
5h 30m
12h 10m
18h 20m
22h 55m
2h 45m
11h 30m
8h 20m
4h 45m
28h
2h 20m
3h
9h 20m
22h 10m
2h 45m
8h 25m
15h 20m
2h 45m
5h 20m
19h 30m
3h
2h 35m
13h 30m
26h
2h 45m
2h 30m
25h 45m
24h 10m
15h 55m
5h 40m
26h 25m
2h 20m
9h 50m
8h
29h 35m
37h 25m
7h 35m
6h 35m
9h 30m
14h 15m
7h 5m
8h
1h 30m
1h 25m
13h 15m
1h 25m
2h 45m
18h 10m
25h 40m
22h
5h 10m
5h 15m
2h 55m
24h
6h 40m
17h 40m
26h 35m
2h 35m
17h 5m
3h 15m
3h 15m
2h 35m
12h 15m
3h 35m
11h 40m
7h 5m
1h 30m
16h 5m
13h 20m
1h 25m
24h 15m
2h 55m
19h 5m
1h 30m
26h 10m
11h 45m
27h 35m
3h
1h 25m
12h 45m
24h
15h 55m
28h 50m
14h
2h 35m
14h 35m
2h 30m
22h 30m
3h
27h
27h 20m
2h 40m
11h 45m
22h 25m
2h 50m
2h 40m
2h 25m
8h 25m
3h 5m
10h 40m
20h
14h 50m
21h 25m
6h
4h 30m
27h 10m
2h 55m
4h 50m
2h 25m
20h
2h 35m
23h 10m
10h 10m
1h 30m
10h 25m
5h 35m
9h
17h 45m
11h 15m
6h 15m
13h 30m
26h 35m
9h
2h 40m
7h 35m
14h 45m
6h 10m
2h 45m
7h 40m
1h 30m
14h 25m
11h 30m
3h 15m
8h 30m
2h 15m
2h 45m
4h 30m
3h 40m
14h
1h 30m
9h 25m
2h 15m
2h 55m
13h 20m
2h 20m
6h 40m
11h 45m
4h 55m
8h 35m
16h 5m
5h 5m
6h 5m
6h 25m
9h 50m
1h 20m
19h 25m
9h 20m
16h 45m
8h 5m
2h 50m
17h 25m
2h 15m
19h 55m
14h 20m
6h 15m
12h
5h 15m
22h 55m
3h
13h 15m
26h
26h
15h 30m
3h
2h 30m
24h
20h 55m
22h
2h 40m
9h 35m
3h
2h 45m
8h
15h
37h 25m
13h 20m
11h 50m
9h 45m
2h 20m
2h 50m
2h 50m
33h 15m
17h 45m
13h 50m
4h 30m
2h 50m
13h 50m
2h 25m
2h 40m
13h 55m
9h 10m
13h 25m
14h 35m
2h 55m
18h 45m
5h 55m
26h 30m
8h 40m
12h 10m
2h 40m
23h 15m
12h 25m
3h
13h 55m
14h 5m
3h
3h 10m
2h 50m
4h 35m
11h 55m
5h 40m
11h 45m
6h 10m
13h 50m
11h 25m
20h 20m
3h
3h 10m
23h 40m
9h 35m
13h 45m
12h 45m
6h 25m
13h 50m
2h 35m
2h 20m
2h 45m
6h 35m
1h 15m
3h
13h 25m
12h 35m
24h 30m
29h 20m
1h 25m
9h 30m
2h 30m
8h 30m
2h 50m
2h 20m
10h 15m
2h 30m
7h 5m
10h 15m
3h 15m
2h 50m
10h 25m
10h 30m
10h 55m
2h 50m
11h 40m
18h 45m
6h 25m
1h 30m
2h 20m
7h 5m
4h 25m
10h 30m
5h 10m
2h 50m
22h 25m
10h
38h
1h 30m
26h 35m
12h 10m
9h 30m
2h 55m
24h 40m
4h 35m
16h 5m
2h 15m
10h 15m
2h 45m
8h
13h 55m
12h 25m
18h 25m
17h 45m
1h 20m
2h 55m
2h 50m
15h 20m
14h 5m
1h 30m
18h 25m
2h 50m
6h
2h 50m
12h 25m
2h 50m
1h 20m
1h 30m
11h 35m
9h 20m
27h 5m
2h 55m
15h 10m
23h 15m
8h 10m
2h 35m
12h 10m
9h 30m
6h 35m
7h 5m
9h 50m
32h 5m
14h 55m
29h 20m
9h 20m
25h
25h 25m
7h 45m
2h 30m
2h 50m
6h 25m
28h 10m
26h 40m
6h 10m
23h 15m
6h 35m
3h 10m
15h 25m
20h 10m
2h 50m
25h 35m
1h 25m
2h 40m
11h 5m
38h 15m
2h 50m
9h 50m
8h
9h 30m
5h 50m
6h
2h 35m
5h
8h 15m
3h
9h
2h 15m
7h
2h 35m
7h 30m
8h 40m
13h 20m
27h
27h 10m
1h 30m
9h
27h 10m
3h 5m
4h
5h 55m
2h 15m
22h 55m
6h 40m
5h 30m
23h
15h 10m
7h 30m
14h
3h
18h 45m
2h 50m
18h 50m
17h 5m
21h 25m
2h 55m
12h 15m
2h 35m
14h 20m
1h 30m
3h
2h 50m
2h 45m
3h 40m
6h
1h 30m
25h 15m
2h 55m
4h 25m
5h
7h 5m
26h 55m
9h 20m
13h
6h
29h 20m
2h 15m
24h 45m
26h 25m
19h 15m
22h 55m
2h 50m
15h 20m
16h
14h 45m
6h 25m
22h 55m
5h
1h 30m
2h 15m
2h 30m
26h 55m
5h 45m
1h 30m
5h 5m
2h 50m
15h 35m
25h
2h 50m
13h 20m
28h 50m

7h 20m
2h 30m
2h 20m
9h 30m
2h 20m
9h 15m
2h 40m
1h 30m
1h 25m
13h 20m
8h 55m
11h 40m
27h
13h 15m
1h 30m
12h 30m
11h 40m
6h 55m
7h 50m
2h 55m
15h 50m
14h 35m
13h 30m
8h 40m
22h 45m
1h 30m
24h 45m
15h 55m
2h 50m
7h 15m
5h 50m
15h 20m
14h 25m
21h 25m
2h 20m
8h 40m
38h 15m
3h 15m
14h 40m
4h 55m
12h 25m
22h
15h 40m
13h
23h 5m
2h 20m
16h 50m
3h
3h
2h 35m
3h
2h 35m
6h 5m
9h 35m
5h 30m
16h 5m
11h 15m
2h 40m
13h 45m
7h 45m
2h 50m
22h 35m
5h 15m
1h 30m
10h 30m
5h 20m
37h 20m
15h 25m
19h 45m
14h 55m
25h 30m
3h
15h 20m
24h 40m
2h 15m
21h 35m
2h 45m
11h 45m
8h 20m
11h 30m
23h 40m
15h 35m
27h 20m
15h 10m
8h 40m
8h
14h 5m
2h 55m
8h 20m
7h 35m
13h 20m
3h
18h 35m
21h 10m
13h 30m
12h 35m
15h 45m
18h 10m
21h 45m
22h 5m
6h 20m
22h
15h 30m
24h
19h 25m
4h 55m
22h 30m
16h 45m
20h 25m
26h 35m
25h 15m
2h 55m
9h
5h 10m
2h 55m
7h 30m
24h 45m
2h 50m
16h 20m
14h 35m
14h 20m
2h 50m
13h 30m
2h 50m
2h 35m
2h 20m
2h 35m
3h 10m
25h
14h 30m
5h 5m
26h 15m
8h 10m
1h 25m
24h 50m
28h
8h 25m
7h 5m
5h
2h 20m
28h 20m
14h 10m
7h 45m
14h
25h
11h 30m
4h 35m
2h 45m
10h 15m
15h 10m
12h 10m
21h 35m
25h 50m
6h 30m
6h 35m
9h
2h 55m
3h
18h 45m
6h 5m
13h
9h 5m
2h 20m
2h 30m
5h 10m
7h 5m
1h 15m
2h 50m
7h 5m
14h 30m
18h 25m
13h 30m
30h 20m
29h 35m
6h 35m
26h 40m
6h 5m
14h 5m
2h 30m
7h 30m
16h 5m
2h 55m
27h 20m
20h 15m
10h 35m
6h 20m
4h
2h 45m
2h 20m
2h 55m
9h 30m
6h 20m
2h 55m
8h 35m
3h
13h 50m
21h
24h 25m
23h
27h 20m
5h 25m
2h 25m
16h 5m
11h 30m
24h 10m
17h 55m
5h 45m
2h 55m
25h 5m
8h 15m
2h 20m
39h 5m
5h
2h 50m
2h 50m
24h 10m
2h 50m
12h
2h 45m
23h 30m
15h
2h 35m
21h 50m
2h 55m
2h 15m
22h 15m
4h 30m
2h 15m
21h 35m
16h 5m
14h 50m
16h 55m
7h 15m
19h 30m
2h 30m
7h
9h 45m
23h 45m
8h 40m
14h 25m
7h 15m
13h 50m
6h 25m
3h
10h 30m
14h 40m
2h 45m
14h 25m
14h 35m
9h 10m
21h 15m
18h 10m
2h 35m
13h 25m
26h 35m
8h 20m
1h 30m
11h 30m
3h 15m
12h
1h 30m
11h 5m
1h 25m
7h 15m
2h 50m
24h
25h 35m
1h 35m
2h 55m
18h 45m
6h 50m
2h 45m
9h 20m
12h 30m
5h 15m
3h
15h 20m
24h 30m
2h 25m
13h 20m
13h 50m
7h 35m
13h 20m
8h 20m
8h 55m
23h 50m
9h 5m
26h 30m
1h 30m
10h 10m
2h 25m
22h 35m
1h 30m
7h 50m
2h 30m
3h 10m
1h 15m
1h 30m
2h 20m
2h 25m
25h 45m
26h 20m
28h
2h 55m
1h 20m
25h 25m
27h 5m
2h 35m
2h 50m
5h 30m
3h 10m
5h 45m
9h 45m
9h 50m
22h 5m
8h 25m
26h 30m
13h 45m
7h 45m
1h 30m
11h
7h 50m
33h 15m
14h 55m
6h
19h 10m
25h 45m
9h 35m
21h 20m
26h 20m
24h 35m
3h
5h 30m
2h 25m
2h 45m
2h 55m
21h 15m
23h 40m
32h 20m
16h 5m
9h 35m
13h 50m
10h 25m
3h
10h 30m
9h 50m
2h 25m
2h 20m
12h 45m
26h 50m
4h 55m
10h 30m
18h 20m
8h 25m
7h 15m
7h 15m
2h 15m
10h 45m
1h 30m
10h 25m
11h 45m
2h 50m
2h 50m
13h 30m
11h 55m
5h 20m
13h 15m
2h 55m
10h 45m
2h 35m
9h
9h 35m
2h 50m
4h 30m
2h 20m
2h 20m
11h 40m
3h 40m
2h 20m
12h 15m
9h 5m
23h 15m
13h 30m
38h 15m
1h 30m
24h 45m
1h 25m
18h 20m
8h 40m
6h 45m
5h 30m
14h 5m
26h 55m
1h 30m
2h 35m
2h 50m
28h 5m
27h
2h 50m
9h 45m
12h 10m
5h
2h 15m
21h 10m
17h 35m
1h 25m
22h 15m
2h 35m
14h 55m
9h 50m
2h 20m
1h 30m
15h 55m
11h 55m
7h 15m
2h 35m
17h 5m
7h 5m
12h 35m
26h 35m
1h 30m
20h 25m
3h 5m
19h 40m
22h 55m
7h 20m
14h 30m
2h 50m
2h 50m
5h
13h 30m
2h 50m
20h 35m
13h 20m
11h 15m
22h 40m
2h 50m
2h 35m
9h 50m
2h 20m
10h 30m
8h 55m
6h 15m
2h 35m
2h 20m
13h 25m
10h 30m
2h 50m
11h 5m
13h 45m
25h 40m
8h 20m
14h 35m
2h 55m
5h 5m
8h 55m
2h 50m
1h 35m
2h 40m
2h 20m
29h 5m
5h 30m
17h 25m
12h
6h 30m
2h 45m
2h 55m
26h 50m
24h 40m
27h 5m
4h 55m
20h 50m
2h 15m
14h 20m
2h 40m
22h 55m
6h 15m
3h 15m
2h 55m
6h 40m
11h
4h 35m
2h 45m
28h
31h 40m
27h 20m
2h 45m
8h 45m
14h 55m
2h 15m
16h 25m
11h 5m
5h
11h 5m
5h 45m
14h 45m
2h 30m
1h 30m
1h 30m
28h 15m
23h 20m
7h 35m
21h 25m
10h 45m
2h 35m
12h 15m
2h 50m
25h 50m
23h
26h
10h 55m
5h 45m
7h 15m
12h 15m
15h 20m
2h 35m
11h 55m
7h 5m
14h 55m
10h 50m
27h 35m
11h 50m
5h 30m
8h 35m
11h
2h 50m
4h 45m
9h 15m
13h 25m
6h 30m
1h 25m
7h 45m
18h 20m
10h
20h 10m
8h 10m
11h 40m
10h 50m
12h 10m
9h 20m
2h 45m
8h
9h 5m
2h 30m
1h 30m
5h 30m
23h 5m
1h 25m
16h 5m
3h
13h 25m
1h 30m
13h 20m
3h
21h 25m
5h 10m
22h
2h 30m
24h 40m
9h
1h 30m
2h 50m
24h 45m
30h 40m
12h 5m
3h 5m
16h 55m
2h 50m
2h 50m
25h 35m
22h
9h 55m
20h 20m
28h 20m
7h 15m
2h 20m
22h 25m
16h 45m
6h 55m
5h 10m
2h 35m
9h 50m
27h 10m
2h 55m
1h 20m
3h
4h 30m
16h 5m
10h 15m
14h 25m
12h 45m
4h 40m
2h 30m
25h 40m
28h 50m
2h 20m
10h 35m
12h 15m
2h 45m
5h
2h 45m
26h 55m
9h 35m
17h 25m
10h 25m
17h 25m
2h 45m
7h 55m
24h 50m
13h 55m
10h 30m
10h 15m
13h 20m
8h 40m
9h 25m
3h 10m
3h 15m
7h 30m
3h
2h 45m
7h 35m
2h 30m
21h 40m
2h 50m
26h 10m
16h 10m
3h 5m
1h 30m
21h 15m
26h 55m
26h 20m
23h
2h 35m
22h 45m
24h 55m
2h 15m
8h 5m
10h
3h
23h 10m
5h 35m
23h 15m
1h 30m
15h 20m
9h 30m
8h 25m
10h 10m
1h 25m
27h 5m
22h 35m
14h 25m
4h 55m
24h
30h 20m
23h 10m
1h 30m
6h 35m
12h
2h 30m
12h 25m
1h 15m
13h 30m
2h 30m
13h 10m
21h 35m
2h 30m
5h 45m
11h 15m
2h 15m
9h 30m
2h 25m
24h
1h 20m
2h 15m
21h 5m
2h 50m
7h 30m
5h 15m
8h 30m
4h 55m
1h 30m
3h
2h 50m
8h 30m
23h 15m
14h 25m
2h 50m
19h
2h 55m
40h 20m
2h 35m
2h 45m
10h 40m
9h 20m
8h 40m
9h
31h 55m
6h 35m
3h
2h 45m
5h 55m
10h 25m
13h 20m
14h 25m
8h 30m
2h 20m
13h
22h 15m
2h 50m
2h 35m
23h 45m
23h 40m
1h 30m
28h 20m
13h 35m
2h 50m
21h
12h 35m
1h 20m
1h 30m
14h
2h 20m
9h 25m
26h
7h 55m
6h 5m
15h 10m
4h 40m
2h 50m
14h 30m
1h 30m
8h 50m
2h 35m
12h 25m
27h 20m
2h 35m
1h 25m
2h 45m
27h
2h 50m
26h 30m
16h 45m
13h
2h 55m
14h 25m
11h 5m
22h 5m
1h 15m
7h 35m
2h 35m
7h 5m
1h 30m
19h 25m
2h 35m
6h 55m
29h 20m
2h 45m
16h 55m
9h 50m
18h 45m
28h 20m
3h 15m
16h 25m
2h 55m
3h
11h 45m
6h 15m
25h 55m
2h 15m
26h 35m
2h 55m
23h 45m
25h 45m
10h
12h 35m
2h 50m
3h
9h 45m
3h 5m
2h 35m
2h 55m
2h 20m
5h 25m
26h 35m
6h 5m
9h 5m
2h 50m
15h 20m
2h 30m
3h
11h 30m
24h 10m
2h 35m
3h
2h 30m
2h 55m
1h 30m
13h 55m
4h 5m
9h 50m
7h 15m
7h 15m
14h 20m
2h 55m
20h 35m
3h
7h 20m
7h 55m
30h 20m
2h 25m
4h 55m
19h 5m
27h 40m
14h 25m
27h 40m
24h 35m
26h 55m
9h 5m
3h 15m
47h 40m
11h 45m
7h 45m
1h 20m
1h 30m
2h 45m
1h 25m
1h 25m
6h 45m
2h 50m
13h 25m
2h 50m
2h 55m
2h 15m
2h 30m
5h 20m
2h 55m
23h 10m
13h 50m
24h 45m
13h 25m
2h 50m
23h 40m
20h 10m
2h 45m
5h 10m
16h 15m
22h 45m
21h 25m
2h 20m
10h 15m
8h 25m
2h 50m
2h 25m
3h 10m
11h
7h 40m
1h 25m
3h 15m
13h 20m
3h
17h 5m
16h 50m
2h 45m
18h 10m
8h 35m
1h 30m
2h 45m
14h 30m
14h
23h 30m
8h 30m
15h 30m
3h 15m
2h 55m
26h 40m
3h
1h 20m
8h 20m
2h 45m
2h 45m
2h 50m
19h 55m
2h 35m
22h 5m
2h 35m
10h 20m
1h 35m
7h 20m
13h
18h 45m
8h 20m
11h 15m
3h
4h
1h 25m
2h 35m
2h 40m
2h 25m
12h 15m
10h 30m
6h 15m
15h 10m
12h 45m
24h 30m
1h 25m
5h 40m
2h 45m
7h 35m
2h 45m
25h 45m
13h 30m
26h 35m
5h 30m
2h 30m
24h 50m
9h 35m
13h 25m
13h 30m
30h 40m
20h 50m
2h 55m
13h 30m
22h 15m
19h 15m
18h 55m
25h 55m
21h 5m
2h 50m
28h 15m
27h 20m
5h 45m
2h 20m
2h 20m
20h 55m
20h
8h 40m
26h 35m
4h 25m
20h 20m
1h 30m
20h 55m
12h 15m
9h 15m
19h 25m
10h 15m
6h 40m
10h 15m
24h 45m
7h 15m
2h 55m
6h 20m
1h 35m
22h 55m
2h 45m
23h
17h 5m
4h 30m
13h 30m
9h 30m
26h 35m
2h 55m
24h 45m
26h 40m
8h 10m
10h 40m
26h 40m
5h 25m
2h 50m
2h 55m
11h 25m
16h 25m
22h 10m
1h 30m
2h 20m
1h 25m
13h 20m
3h 5m
15h 15m
2h 55m
26h 55m
1h 30m
2h 35m
5h 45m
2h 35m
2h 35m
16h 10m
19h 55m
26h 20m
7h 20m
2h 55m
22h 15m
5h 30m
9h 5m
26h 45m
5h 45m
17h 55m
7h 15m
26h 55m
13h 45m
5h 30m
3h 5m
14h
38h
24h 35m
2h 20m
26h 50m
6h 30m
8h 25m
8h 25m
13h 30m
3h 15m
26h 20m
2h 40m
8h 25m
7h 40m
25h 35m
21h 55m
2h 40m
1h 25m
2h 40m
13h 20m
2h 55m
2h 50m
2h 55m
6h 15m
20h 10m
17h 5m
2h 55m
2h 30m
24h 45m
21h 25m
7h 20m
11h 15m
17h 25m
1h 20m
19h 55m
15h
24h 45m
1h 20m
8h 40m
2h 40m
2h 30m
2h 35m
3h
2h 40m
8h 20m

In [102]:
for i , d in enumerate(data.Duration):
    d = d.split()
    if len(d) == 2:
        data.loc[i,'d_mins'] = int(d[0].replace('h',''))*60 + int(d[1].replace('m',''))
    elif 'h' in d[0]:
        data.loc[i,'d_mins'] = int(d[0].replace('h',''))*60
    elif 'm' in d[0]:
        data.loc[i,'d_mins'] = int(d[0].replace('m',''))

In [103]:
for i,dur in enumerate(data.Duration):
    dur = dur.split()
    if len(dur) == 2:
        data.loc[i,'dur_mins']=int(dur[0].replace('h',''))*60+int(dur[1].replace('m','')) # i indicates the index number
    elif 'h' in dur[0]:
        data.loc[i,'dur_mins']=int(dur[0].replace('h',''))*60
    elif 'm' in dur[0]:
        data.loc[i,'dur_mins']=int(dur[0].replace('m',''))

In [88]:
data

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,dur_mins,d_mins
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,170.0,170.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,445.0,445.0
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,1140.0,1140.0
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,325.0,325.0
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,285.0,285.0
5,SpiceJet,24/06/2019,Kolkata,Banglore,CCU → BLR,09:00,11:25,2h 25m,non-stop,No info,3873,145.0,145.0
6,Jet Airways,12/03/2019,Banglore,New Delhi,BLR → BOM → DEL,18:55,10:25 13 Mar,15h 30m,1 stop,In-flight meal not included,11087,930.0,930.0
7,Jet Airways,01/03/2019,Banglore,New Delhi,BLR → BOM → DEL,08:00,05:05 02 Mar,21h 5m,1 stop,No info,22270,1265.0,1265.0
8,Jet Airways,12/03/2019,Banglore,New Delhi,BLR → BOM → DEL,08:55,10:25 13 Mar,25h 30m,1 stop,In-flight meal not included,11087,1530.0,1530.0
9,Multiple carriers,27/05/2019,Delhi,Cochin,DEL → BOM → COK,11:25,19:15,7h 50m,1 stop,No info,8625,470.0,470.0
10,Air India,1/06/2019,Delhi,Cochin,DEL → BLR → COK,09:45,23:00,13h 15m,1 stop,No info,8907,795.0,795.0
11,IndiGo,18/04/2019,Kolkata,Banglore,CCU → BLR,20:20,22:55,2h 35m,non-stop,No info,4174,155.0,155.0
12,Air India,24/06/2019,Chennai,Kolkata,MAA → CCU,11:40,13:55,2h 15m,non-stop,No info,4667,135.0,135.0
13,Jet Airways,9/05/2019,Kolkata,Banglore,CCU → BOM → BLR,21:10,09:20 10 May,12h 10m,1 stop,In-flight meal not included,9663,730.0,730.0
14,IndiGo,24/04/2019,Kolkata,Banglore,CCU → BLR,17:15,19:50,2h 35m,non-stop,No info,4804,155.0,155.0
15,Air India,3/03/2019,Delhi,Cochin,DEL → AMD → BOM → COK,16:40,19:15 04 Mar,26h 35m,2 stops,No info,14011,1595.0,1595.0
16,SpiceJet,15/04/2019,Delhi,Cochin,DEL → PNQ → COK,08:45,13:15,4h 30m,1 stop,No info,5830,270.0,270.0
17,Jet Airways,12/06/2019,Delhi,Cochin,DEL → BOM → COK,14:00,12:35 13 Jun,22h 35m,1 stop,In-flight meal not included,10262,1355.0,1355.0
18,Air India,12/06/2019,Delhi,Cochin,DEL → CCU → BOM → COK,20:15,19:15 13 Jun,23h,2 stops,No info,13381,1380.0,1380.0
19,Jet Airways,27/05/2019,Delhi,Cochin,DEL → BOM → COK,16:00,12:35 28 May,20h 35m,1 stop,In-flight meal not included,12898,1235.0,1235.0
20,GoAir,6/03/2019,Delhi,Cochin,DEL → BOM → COK,14:10,19:20,5h 10m,1 stop,No info,19495,310.0,310.0
21,Air India,21/03/2019,Banglore,New Delhi,BLR → COK → DEL,22:00,13:20 19 Mar,15h 20m,1 stop,No info,6955,920.0,920.0
22,IndiGo,3/04/2019,Banglore,Delhi,BLR → DEL,04:00,06:50,2h 50m,non-stop,No info,3943,170.0,170.0
23,IndiGo,1/05/2019,Banglore,Delhi,BLR → DEL,18:55,21:50,2h 55m,non-stop,No info,4823,175.0,175.0
24,Jet Airways,6/05/2019,Kolkata,Banglore,CCU → BOM → BLR,18:55,08:15 07 May,13h 20m,1 stop,In-flight meal not included,7757,800.0,800.0
25,Jet Airways,9/06/2019,Delhi,Cochin,DEL → IDR → BOM → COK,21:25,12:35 10 Jun,15h 10m,2 stops,No info,13292,910.0,910.0
26,IndiGo,1/06/2019,Delhi,Cochin,DEL → LKO → COK,21:50,03:35 02 Jun,5h 45m,1 stop,No info,8238,345.0,345.0
27,GoAir,15/05/2019,Delhi,Cochin,DEL → BOM → COK,07:00,12:55,5h 55m,1 stop,No info,7682,355.0,355.0
28,Vistara,18/06/2019,Banglore,Delhi,BLR → DEL,09:45,12:35,2h 50m,non-stop,No info,4668,170.0,170.0
29,Vistara,15/06/2019,Chennai,Kolkata,MAA → CCU,07:05,09:20,2h 15m,non-stop,No info,3687,135.0,135.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10653,Jet Airways,1/05/2019,Kolkata,Banglore,CCU → BOM → BLR,14:05,12:00 02 May,21h 55m,1 stop,No info,14388,1315.0,1315.0
10654,SpiceJet,12/06/2019,Banglore,Delhi,BLR → DEL,05:55,08:35,2h 40m,non-stop,No check-in baggage included,4319,160.0,160.0
10655,Jet Airways,3/05/2019,Mumbai,Hyderabad,BOM → HYD,02:55,04:20,1h 25m,non-stop,No info,5678,85.0,85.0
10656,Vistara,6/04/2019,Banglore,Delhi,BLR → DEL,07:00,09:40,2h 40m,non-stop,No info,5613,160.0,160.0
10657,Jet Airways,6/05/2019,Kolkata,Banglore,CCU → BOM → BLR,20:00,09:20 07 May,13h 20m,1 stop,In-flight meal not included,9663,800.0,800.0
10658,Jet Airways,18/06/2019,Banglore,Delhi,BLR → DEL,11:10,14:05,2h 55m,non-stop,In-flight meal not included,5769,175.0,175.0
10659,Vistara,1/05/2019,Banglore,Delhi,BLR → DEL,21:00,23:50,2h 50m,non-stop,No info,4668,170.0,170.0
10660,Vistara,21/03/2019,Banglore,New Delhi,BLR → DEL,21:10,00:05 19 Mar,2h 55m,non-stop,No info,4878,175.0,175.0
10661,Air India,9/05/2019,Delhi,Cochin,DEL → BOM → COK,13:00,19:15,6h 15m,1 stop,No info,8372,375.0,375.0
10662,Air India,24/03/2019,Kolkata,Banglore,CCU → BOM → GOI → BLR,09:25,05:35 25 Mar,20h 10m,2 stops,No info,12352,1210.0,1210.0
10663,Jet Airways,6/06/2019,Delhi,Cochin,DEL → JAI → BOM → COK,19:30,12:35 07 Jun,17h 5m,2 stops,In-flight meal not included,11733,1025.0,1025.0
10664,IndiGo,9/04/2019,Banglore,Delhi,BLR → DEL,18:55,21:50,2h 55m,non-stop,No info,4823,175.0,175.0
10665,IndiGo,27/04/2019,Kolkata,Banglore,CCU → BLR,15:15,17:45,2h 30m,non-stop,No info,4804,150.0,150.0
10666,Jet Airways,12/06/2019,Delhi,Cochin,DEL → BOM → COK,18:15,19:00 13 Jun,24h 45m,1 stop,In-flight meal not included,10262,1485.0,1485.0
10667,Jet Airways,12/03/2019,Banglore,New Delhi,BLR → BOM → DEL,22:55,20:20 13 Mar,21h 25m,1 stop,In-flight meal not included,11087,1285.0,1285.0
10668,Jet Airways,9/05/2019,Delhi,Cochin,DEL → JDH → BOM → COK,11:40,19:00,7h 20m,2 stops,No info,21219,440.0,440.0
10669,Air India,15/06/2019,Delhi,Cochin,DEL → BOM → COK,08:00,19:15,11h 15m,1 stop,No info,9929,675.0,675.0
10670,Air India,12/05/2019,Kolkata,Banglore,CCU → IXR → DEL → BLR,05:50,23:15,17h 25m,2 stops,No info,11411,1045.0,1045.0
10671,Air India,6/06/2019,Mumbai,Hyderabad,BOM → HYD,21:05,22:25,1h 20m,non-stop,No info,3100,80.0,80.0
10672,Jet Airways,27/06/2019,Delhi,Cochin,DEL → AMD → BOM → COK,23:05,19:00 28 Jun,19h 55m,2 stops,In-flight meal not included,11150,1195.0,1195.0
10673,Jet Airways,27/05/2019,Delhi,Cochin,DEL → AMD → BOM → COK,13:25,04:25 28 May,15h,2 stops,No info,16704,900.0,900.0
10674,Jet Airways,12/03/2019,Banglore,New Delhi,BLR → BOM → DEL,20:35,21:20 13 Mar,24h 45m,1 stop,In-flight meal not included,11087,1485.0,1485.0
10675,Air India,9/06/2019,Mumbai,Hyderabad,BOM → HYD,06:20,07:40,1h 20m,non-stop,No info,3100,80.0,80.0
10676,Multiple carriers,1/05/2019,Delhi,Cochin,DEL → BOM → COK,10:20,19:00,8h 40m,1 stop,No info,9794,520.0,520.0
10677,SpiceJet,21/05/2019,Banglore,Delhi,BLR → DEL,05:55,08:35,2h 40m,non-stop,No check-in baggage included,3257,160.0,160.0
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,150.0,150.0
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,155.0,155.0
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,180.0,180.0
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,160.0,160.0
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,500.0,500.0

In [89]:
import numpy as np

In [120]:
data

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
5,SpiceJet,24/06/2019,Kolkata,Banglore,CCU → BLR,09:00,11:25,2h 25m,non-stop,No info,3873
6,Jet Airways,12/03/2019,Banglore,New Delhi,BLR → BOM → DEL,18:55,10:25 13 Mar,15h 30m,1 stop,In-flight meal not included,11087
7,Jet Airways,01/03/2019,Banglore,New Delhi,BLR → BOM → DEL,08:00,05:05 02 Mar,21h 5m,1 stop,No info,22270
8,Jet Airways,12/03/2019,Banglore,New Delhi,BLR → BOM → DEL,08:55,10:25 13 Mar,25h 30m,1 stop,In-flight meal not included,11087
9,Multiple carriers,27/05/2019,Delhi,Cochin,DEL → BOM → COK,11:25,19:15,7h 50m,1 stop,No info,8625
10,Air India,1/06/2019,Delhi,Cochin,DEL → BLR → COK,09:45,23:00,13h 15m,1 stop,No info,8907
11,IndiGo,18/04/2019,Kolkata,Banglore,CCU → BLR,20:20,22:55,2h 35m,non-stop,No info,4174
12,Air India,24/06/2019,Chennai,Kolkata,MAA → CCU,11:40,13:55,2h 15m,non-stop,No info,4667
13,Jet Airways,9/05/2019,Kolkata,Banglore,CCU → BOM → BLR,21:10,09:20 10 May,12h 10m,1 stop,In-flight meal not included,9663
14,IndiGo,24/04/2019,Kolkata,Banglore,CCU → BLR,17:15,19:50,2h 35m,non-stop,No info,4804
15,Air India,3/03/2019,Delhi,Cochin,DEL → AMD → BOM → COK,16:40,19:15 04 Mar,26h 35m,2 stops,No info,14011
16,SpiceJet,15/04/2019,Delhi,Cochin,DEL → PNQ → COK,08:45,13:15,4h 30m,1 stop,No info,5830
17,Jet Airways,12/06/2019,Delhi,Cochin,DEL → BOM → COK,14:00,12:35 13 Jun,22h 35m,1 stop,In-flight meal not included,10262
18,Air India,12/06/2019,Delhi,Cochin,DEL → CCU → BOM → COK,20:15,19:15 13 Jun,23h,2 stops,No info,13381
19,Jet Airways,27/05/2019,Delhi,Cochin,DEL → BOM → COK,16:00,12:35 28 May,20h 35m,1 stop,In-flight meal not included,12898
20,GoAir,6/03/2019,Delhi,Cochin,DEL → BOM → COK,14:10,19:20,5h 10m,1 stop,No info,19495
21,Air India,21/03/2019,Banglore,New Delhi,BLR → COK → DEL,22:00,13:20 19 Mar,15h 20m,1 stop,No info,6955
22,IndiGo,3/04/2019,Banglore,Delhi,BLR → DEL,04:00,06:50,2h 50m,non-stop,No info,3943
23,IndiGo,1/05/2019,Banglore,Delhi,BLR → DEL,18:55,21:50,2h 55m,non-stop,No info,4823
24,Jet Airways,6/05/2019,Kolkata,Banglore,CCU → BOM → BLR,18:55,08:15 07 May,13h 20m,1 stop,In-flight meal not included,7757
25,Jet Airways,9/06/2019,Delhi,Cochin,DEL → IDR → BOM → COK,21:25,12:35 10 Jun,15h 10m,2 stops,No info,13292
26,IndiGo,1/06/2019,Delhi,Cochin,DEL → LKO → COK,21:50,03:35 02 Jun,5h 45m,1 stop,No info,8238
27,GoAir,15/05/2019,Delhi,Cochin,DEL → BOM → COK,07:00,12:55,5h 55m,1 stop,No info,7682
28,Vistara,18/06/2019,Banglore,Delhi,BLR → DEL,09:45,12:35,2h 50m,non-stop,No info,4668
29,Vistara,15/06/2019,Chennai,Kolkata,MAA → CCU,07:05,09:20,2h 15m,non-stop,No info,3687
...,...,...,...,...,...,...,...,...,...,...,...
10653,Jet Airways,1/05/2019,Kolkata,Banglore,CCU → BOM → BLR,14:05,12:00 02 May,21h 55m,1 stop,No info,14388
10654,SpiceJet,12/06/2019,Banglore,Delhi,BLR → DEL,05:55,08:35,2h 40m,non-stop,No check-in baggage included,4319
10655,Jet Airways,3/05/2019,Mumbai,Hyderabad,BOM → HYD,02:55,04:20,1h 25m,non-stop,No info,5678
10656,Vistara,6/04/2019,Banglore,Delhi,BLR → DEL,07:00,09:40,2h 40m,non-stop,No info,5613
10657,Jet Airways,6/05/2019,Kolkata,Banglore,CCU → BOM → BLR,20:00,09:20 07 May,13h 20m,1 stop,In-flight meal not included,9663
10658,Jet Airways,18/06/2019,Banglore,Delhi,BLR → DEL,11:10,14:05,2h 55m,non-stop,In-flight meal not included,5769
10659,Vistara,1/05/2019,Banglore,Delhi,BLR → DEL,21:00,23:50,2h 50m,non-stop,No info,4668
10660,Vistara,21/03/2019,Banglore,New Delhi,BLR → DEL,21:10,00:05 19 Mar,2h 55m,non-stop,No info,4878
10661,Air India,9/05/2019,Delhi,Cochin,DEL → BOM → COK,13:00,19:15,6h 15m,1 stop,No info,8372
10662,Air India,24/03/2019,Kolkata,Banglore,CCU → BOM → GOI → BLR,09:25,05:35 25 Mar,20h 10m,2 stops,No info,12352
10663,Jet Airways,6/06/2019,Delhi,Cochin,DEL → JAI → BOM → COK,19:30,12:35 07 Jun,17h 5m,2 stops,In-flight meal not included,11733
10664,IndiGo,9/04/2019,Banglore,Delhi,BLR → DEL,18:55,21:50,2h 55m,non-stop,No info,4823
10665,IndiGo,27/04/2019,Kolkata,Banglore,CCU → BLR,15:15,17:45,2h 30m,non-stop,No info,4804
10666,Jet Airways,12/06/2019,Delhi,Cochin,DEL → BOM → COK,18:15,19:00 13 Jun,24h 45m,1 stop,In-flight meal not included,10262
10667,Jet Airways,12/03/2019,Banglore,New Delhi,BLR → BOM → DEL,22:55,20:20 13 Mar,21h 25m,1 stop,In-flight meal not included,11087
10668,Jet Airways,9/05/2019,Delhi,Cochin,DEL → JDH → BOM → COK,11:40,19:00,7h 20m,2 stops,No info,21219
10669,Air India,15/06/2019,Delhi,Cochin,DEL → BOM → COK,08:00,19:15,11h 15m,1 stop,No info,9929
10670,Air India,12/05/2019,Kolkata,Banglore,CCU → IXR → DEL → BLR,05:50,23:15,17h 25m,2 stops,No info,11411
10671,Air India,6/06/2019,Mumbai,Hyderabad,BOM → HYD,21:05,22:25,1h 20m,non-stop,No info,3100
10672,Jet Airways,27/06/2019,Delhi,Cochin,DEL → AMD → BOM → COK,23:05,19:00 28 Jun,19h 55m,2 stops,In-flight meal not included,11150
10673,Jet Airways,27/05/2019,Delhi,Cochin,DEL → AMD → BOM → COK,13:25,04:25 28 May,15h,2 stops,No info,16704
10674,Jet Airways,12/03/2019,Banglore,New Delhi,BLR → BOM → DEL,20:35,21:20 13 Mar,24h 45m,1 stop,In-flight meal not included,11087
10675,Air India,9/06/2019,Mumbai,Hyderabad,BOM → HYD,06:20,07:40,1h 20m,non-stop,No info,3100
10676,Multiple carriers,1/05/2019,Delhi,Cochin,DEL → BOM → COK,10:20,19:00,8h 40m,1 stop,No info,9794
10677,SpiceJet,21/05/2019,Banglore,Delhi,BLR → DEL,05:55,08:35,2h 40m,non-stop,No check-in baggage included,3257
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [121]:
data.loc[data.Total_Stops == 'non-stop','Stops'] = 0
data.loc[data.Total_Stops == '2 stops','Stops'] = 2
data.loc[data.Total_Stops == '1 stop','Stops'] = 1

In [127]:
int((data.Stops))

TypeError: cannot convert the series to <class 'int'>

In [148]:
for i in data.Stops:
        data.loc[i,'stps'] = int(i)

ValueError: cannot convert float NaN to integer

In [144]:
# x contained NaN
data.Stops = data.Stops[~data.Stops[''].isnull()]

# Y contained some other garbage, so null check was not enough
df = df[df['y'].str.isnumeric()]

# final conversion now worked
df[['x']] = df[['x']].astype(int)
df[['y']] = df[['y']].astype(int)

AttributeError: 'Series' object has no attribute 'unique_values'

In [155]:
data[['Stops']] = data[['Stops']].astype(int)

ValueError: Cannot convert non-finite values (NA or inf) to integer

In [152]:
data.Stops = data.Stops[~data.Stops[''].isnull()]

KeyError: ''

In [157]:
type(np.nan)

float

In [158]:
data.Stops= data.Stops.fillna(0).astype(int)

In [159]:
np.unique(data.Stops)

array([0, 1, 2])

In [160]:
data.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Stops,stps
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,0,0.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,2,1.0
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,2,2.0
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,1,NaN
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,NaN

In [163]:
data.stps = data.Stops.copy()

In [164]:
data.stps

0        0
1        2
2        2
3        1
4        1
5        0
6        1
7        1
8        1
9        1
10       1
11       0
12       0
13       1
14       0
15       2
16       1
17       1
18       2
19       1
20       1
21       1
22       0
23       0
24       1
25       2
26       1
27       1
28       0
29       0
        ..
10653    1
10654    0
10655    0
10656    0
10657    1
10658    0
10659    0
10660    0
10661    1
10662    2
10663    2
10664    0
10665    0
10666    1
10667    1
10668    2
10669    1
10670    2
10671    0
10672    2
10673    2
10674    1
10675    0
10676    1
10677    0
10678    0
10679    0
10680    0
10681    0
10682    2
Name: stps, Length: 10683, dtype: int32